---
title: E80 Team Contract Specs
format:
  html: default
  docx: default
---

## Team Contract Specifications

### Effort

- [ ] Mission statement present.
- [ ] Logistics includes communication medium and agreed upon norms.
- [ ] Group data storage system created (e.g., shared Drive or shared folder on Google Drive).
- [ ] DOCX version of team contract uploaded into shared drive for group editing.
- [ ] Objectives present for team.

### Completion

- [ ] Team mission is clear and concise.
- [ ] Logistics and organization section clearly outlines communication and collaboration methods and expectations.
- [ ] Strengths and weaknesses are included for each team member.
- [ ] Team objectives are clear, specific, and include metrics to assess how the team is performing.
- [ ] Team norms explain what they will do to create a high-functioning team, how they will know when things are going
- [ ] All team members have signed the form.
 

### Comments

Add specific notes here about the assignment and what is yet to be completed.

<textarea id="comments" name="comments" rows="10" cols="50">

</textarea>