---
title: E80 Team Contract
format:
  html: default
  docx: default
---

::: {.content-visible when-format="html"}
::: {.callout-note}

This page contains notes to highlight the purpose and suggested comment for each section.
These comments will only appear on the web, not in the MS Word version of the template.
:::
:::

E80, Section #: \_\_\_\_\_\_\_ Team \# \_\_\_\_\_\_

## Team Members

|     | Team Member |
|-----|-------------|
| 1\. |             |
| 2\. |             |
| 3\. |             |
| 4\. |             |
| 5\. |             |

You can complete this contract only after having your consensus-building discussion!

## Mission

::: {.content-visible when-format="html"}
::: {.callout-note}

Team members share truthfully what they want from their E80 team experience. Identify and describe your team’s mission which will serve you as a guide for setting priorities, making decisions and how members will work together.

:::
:::

We agree that the purpose of our team is…

::: {.content-visible when-format="html"}
::: {.callout-note title="Example from an E4 team"}
 The purpose of our team is to use the process of creating a successful composting design as an avenue to develop both our engineering and interpersonal skills. We strive to maintain a positive team dynamic by allocating tasks fairly and communicating both regularly and effectively.
:::
:::

## Logistics / Organization

::: {.content-visible when-format="html"}
::: {.callout-note title="Organization Information to Include"}
Describe in detail how you will:

-   Communicate with each other
    -    Medium (e.g., email, text, Discord)
    -    Frequency
    -    Expected response time
-   Store, update, and exchange information (Google Drive, Discord, Slack, etc.)
-   Hold effective meetings (Schedule, Agenda, Roles, Meeting Minutes, etc.)
-   Track task progress & completion (who will do what by when?)
:::
:::

## Strengths & Weaknesses

::: {.content-visible when-format="html"}

::: {.callout-note title="Strengths & Weaknesses"}

List here each team member’s strengths (e.g., strong Python skills, detail oriented, inclusive, focus on excellence, doer attitude, loves research, positive attitude, etc.) and weaknesses (tends to speak a lot, tends to speak very little, no CAD experience, tends to be late for meetings, etc.), how each team member plans to apply their strengths to the team’s success, and how each team member plans to work on improving/compensating their weaknesses.

:::
:::

### Team Member 1: 

**Strengths**

-  

**Weaknesses**

-  

### Team Member 2: 

**Strengths**

-  

**Weaknesses**


### Team Member 3:

**Strengths**

-  

**Weaknesses**

-  

### Team Member 4:

**Strengths**

-  

**Weaknesses**

-  

### Team Member 5: 

**Strengths**

-  

**Weaknesses**

-  

## Objectives

::: {.content-visible when-format="html"}

::: {.callout-note title="Example Team Objectives"}

Describe in detail your team’s objectives:

-   Grades
-   Quality of work
-   Desired participation of team members and how will you measure it
-   Distribution of work
-   Development of specific technical skills
-   Development of teamwork skills

:::
:::

## Team Norms

::: {.content-visible when-format="html"}
::: {.callout-note title="Example Team Norms"}

Describe in detail your team’s rules of engagement:

-   How the team will create and maintain psychological safety
-   How you will ensure to create a healthy feedback culture
-   How your team makes decisions
-   How your team handles & resolves conflicts
-   How you hold each other accountable
-   The consequences for breaking rules
-   Anything else important for your team (e.g., humor)
 
:::
:::

## Team Signatures

a.  I participated in formulating the mission, logistics, strengths and weaknesses, objectives, and ground rules as stated in this contract.
b.  I understand that I am obligated to abide by these terms and conditions.
c.  I understand that if I do not abide by these terms and conditions, I will suffer the consequences as stated in this contract.

| Team Member | Date |
|-------------|------|
| 1\.         |      |
| 2\.         |      |
| 3\.         |      |
| 4\.         |      |
| 5\.         |      |