---
title: E80 Team Contract
---

## Team Contract Template

### Contract
[View](./team-contract-template.html) or [download](./team-contract-template.docx) the team contract template.

### Specs
[View](./team-contract-specs.html) or [download](./team-contract-specs.docx) the team contract specifications.

## Guidelines for Writing a Team Contract

E80 is a team-based class and you will work with other students to complete a collaborative project. To accelerate your team’s development, you will create and sign a team contract as a result of having an engaged conversation in which ALL team members contribute.

Please notice that your team contract is a living document which should be re-visited often and updated as necessary.

### Stages of Team Development

According to concepts from Organizational Behavior, there are five stages of team development:

1.  Forming
2.  Storming
3.  Norming
4.  Performing
5.  Adjourning

During the **forming** stage, teams tend to communicate in indirect polite ways rather than more directly. The **storming** stage, characterized by conflict, can be productive, but may consume excessive amounts of time and energy. In this stage it is important to listen well for differing expectations. Next, during the **norming** stage, teams formulate roles and standards, increasing trust and communication. This norming stage is characterized by agreement on procedures, reduction in role ambiguity, and increased “we-ness” or unity.\
These developments generally are precursors to the **performing** stage, during which teams achieve their goals, are highly task oriented, and focus on performance and production. When the task has been completed, the team enters the **adjourning** phase.

### Team Contract Purpose

To accelerate a team’s development, a team contract is generated in order to move the team more quickly into the performing stage. This process of generating a team contract can actually help jump-start a group's collaborative efforts by immediately focusing the team members on a definite task. The group members must communicate and negotiate in order to identify the quality of work they all wish to achieve, and the level of group participation and individual accountability they all feel comfortable with.

Successful team performance depends on personal individual accountability. Conflicts can arise when individualistic motives or behaviors disrupt team-oriented goals. For example, conflict can stem from an unequal division of resources. When team members believe they are receiving too little for what they are giving, they sometimes reduce their effort and turn in work of lower quality. Such "free riding" occurs most frequently when individual contributions are combined into a single product or performance, and individual effort is perceived as unequal. At this point, some individual team members may take on extra responsibilities while other team members may reduce their own efforts or withdraw from the team completely. These behaviors may engender anger, frustration, or isolation—resulting in a dysfunctional team and poor quality of work. However, with a well-formulated team contract, such obstacles can usually be avoided.

Once your team contract has been developed, your team is ready to begin work on collaborative assignments. However, you may soon find that your team is not working as well as you had hoped. This is normal but needs to be attended to immediately. Perhaps your team is simply not following the established rules and agreements as strictly as you should be, or perhaps you need to change parts of your contract. Call a team meeting immediately to discuss and resolve the challenges your team is facing; do not delay. Seek guidance from your instructor to resolve any conflicts so that you will have the most positive team experience possible.