---
title: E80 Abstract Writing Assignment
format:
  revealjs:
    slide-number: true
---

## Abstract

General formula for abstracts, 1 sentence each for the following items:

- What did you do?
- How did you do it?
- What is your most meaningful, quantitative result?
- Why did you do it / what does that result mean?

Don’t put in too much stuff! It’s not an introduction.

## Statement of Work

In this writing assignment you will write an abstract for the work you did in lab this week.
Be sure to follow the conventions of an abstract carefully:

- Don’t summarize more of your work than necessary.
- Do include quantitative results.
- Keep it short.

## Learning Objectives

By the end of this writing assignment you will...

- Learn to write an abstract that follows the conventions of scientific writing. 

## Specifications {.smaller}

### Effort

- [ ] Abstract is present.

### Completion

- [ ]	Concisely summarizes the gist of each section of the lab report.
- [ ]	Arranges the sentences in the order the sections are presented in the lab report.
- [ ]	Is self-sufficient and does not rely on results presented only in the body of the report.
- [ ]	Uses past tense to report what was done.
- [ ]	Stays within the maximum words allowed (usually 100-200 words).
