---
title: "Lab Overview"
---

Lab manuals are linked here.

* Note that the project is sub-divided into six parts as described below.   
* Deliverables for each lab and the project are detailed on their individual pages.
* Note that in weeks 6 and 7, the order of Lectures/quiz/Lab are not the same for everyone. Odd numbered teams are in Group A and Even numbered teams are in Group B. **Please make sure prelab is done for the correct lab.**

# Labs


| Week            | Group A<br>(Odd numbered teams) | Group B<br>(Even numbered teams) |
|----------------------|----------------|---------------------|
| **1** (1/16-1/19)|  [Lab 0:<br>Tutorial and Skill Review](/labs/lab0)  |  [Lab 0:<br>Tutorial and Skill Review](/labs/lab0)  |
| **2** (1/22-1/26)|  [Lab 1:<br>Go Autonomous](/labs/lab1)  |  [Lab 1:<br>Go Autonomous](/labs/lab1)  |
| **3** (1/29-2/2)|  [Lab 2:<br>Basic Electrical Measurements](/labs/lab2)  |  [Lab 2:<br>Basic Electrical Measurements](/labs/lab2)  |
| **4** (2/5-2/9)|  [Lab 3:<br>Op Amps and Marine Sensors](/labs/lab3)  |  [Lab 3:<br>Op Amps and Marine Sensors](/labs/lab3)  |
| **5** (2/12-2/16)|  [Lab 4:<br>Temperature Sensors](/labs/lab4)  |  [Lab 4:<br>Temperature Sensors](/labs/lab4)  |
| **6** (2/19-2/23)|  [Lab 5:<br>Underwater Acoustics](/labs/lab5)  |  [Lab 6:<br>Fluid Mechanics](/labs/lab6)  |
| **7** (2/26-3/1)|  [Lab 6:<br>Fluid Mechanics](/labs/lab6)  |  [Lab 5:<br>Underwater Acoustics](/labs/lab5)  |
| **8** (3/4-3/8)|  [Project week 1:](/project)    Propose and Design
| **9** (3/11-3/15)|  **Spring Break**  |  
| **10** (3/18-3/22)|  [Lab 7:<br>Project Boot Camp (ver 2)](/labs/lab7)  |  [Lab 7:<br>Project Boot Camp (ver 1)](/labs/lab7)  |
| **11** (3/25-3/29)|  [Project week 2: ](/project)  Breadboard and Test
| **12** (4/1-4/5)|  [Project week 3: ](/project)  PCB Solder and Test 
| **13** (4/8-4/12)|  [Project week 4: ](/project) Launch at pHake Lake  
| **14** (4/15-4/19)|  [Project week 5:](/project)  Rebuild, retest
| **15** (4/22-4/26)|  [Project week 6:](/project)   Analysis
__________
- **Saturday 4/20/2024**   <br>Relaunch at Dana Point<br>**ALL STUDENTS ARE EXPECTED TO ATTEND THE SATURDAY LAUNCH**

- **Wednesday 5/1/2024**   <br>**PROJECT PRESENTATION FOR ALL GROUPS**





# Safety Rules in E80

## General rules
- No eating or drinking in lab. If necessary you may leave lab, wash your hands, eat and/or drink something outside the lab, wash your hands, return to lab.
- Know the location of fire extinguisher, eye wash, safety shower and quickest escape route.
- Notify instructor immediately after _any_ injury, fire, spills or breakage.
- Clean lab bench and turn off equipment before leaving. Leave the bench power on.
- Electricity and water DO NOT MIX –a lot of water is involved in E80 – be mindful at all times.

## Proper attire
- Closed-toe shoes
- Short sleeves preferred, rolled-up long sleeves acceptable
- Long pants
- No dangling jewelry – no rings, bracelets, necklaces or earrings
- Loose clothing must be secured away from work (including hoody draw strings)
- Long hair pulled back and secured
- For field experiences:
  - Location-appropriate footwear and clothing
  - Appropriate PPE (including floatation devices for boats)
  - Sunscreen
  - Hydration

## Chemical safety: epoxies and CA (CyanoAcrylate aka superglue)
- Safety goggles
- Gloves
- If procedure emits fumes, then must be done in a fume hood or out of doors away from buildings

## Soldering
- Iron must be turned off when not in your hand.
- Use recently soaked sponge. Use spray bottle to moisten. Never use sink or water fountain.
- Use fume extractor: fume from rosin in solder is a respiratory irritant.
- Wash hands after handling solder – solder is 40% lead.  Skin contact is harmless, but ingestion can occur with unwashed hands when eating, drinking, or smoking.

# Lab Practices

## Deliverables
A submission sheet is due at the end of each 4-hour lab period. The submission sheet must be uploaded before the end of your lab session at 5:15 pm. Note that only **ONE** member of each team should access and submit the submission sheet. It is the responsibility of that team member to add the rest of the team’s names to the submission sheet. 

## Hardware checkout
You will work with some expensive hardware in this class. Expensive hardware like motherboards and batteries must be explicitly checked out from a professor or proctor so that we can track where it is. If any hardware that you checked out breaks,  you will need to request a replacement from a professor. You make this request by filling out an [error report](https://drive.google.com/open?id=1FnHDzDSCuc3pAsEXzUg6BnTacfLF-ODs) (paper copies will be in lab). This report needs to be well thought out; professors will reject reports that don't represent sufficient testing or thought. You will keep this hardware with you throughout the semester in your storage box. 


## SAFETY QUESTIONs
Labs will include callout boxes labeled "SAFETY QUESTION: the question text".  ALL group members must be able to answer these questions before the lab.  Failing to understand the SAFETY QUESTIONs can damage equipment or harm lab users.  You should always feel empowered to stop work and grab an instructor if you find a safety question that makes you unsure.

## Work breakdown and prelab
It is up to the team to determine which parts of the lab are done by whom, and at what time during the four hours of lab time. No hardware can be used outside of lab hours and no real data can be processed outside of lab hours. However, writing software or processing simulated data sets is allowed and, in fact, encouraged during the pre-lab period.


# Inclusion
HMC is committed to providing an inclusive learning environment and support for all students. Students with a disability (including mental health, chronic or temporary medical conditions) who may need accommodations in order to fully participate in this class are encouraged to contact the Office of Accessible Education at [access@g.hmc.edu](mailto:access@g.hmc.edu) to request accommodations. Students from the other Claremont Colleges should contact their home college's Accessible Education officer.
