---
title: "Lab 6: Fluid Dynamics"
---

Team size: 4


## Learning Objectives

After successful completion of this lab, you will be able to…



1. Perform computational fluid dynamics simulations in COMSOL Multiphysics.
2. Use the wind tunnel to perform experiments to verify the results of your fluid dynamics simulations.


## 0. Introduction

This lab will take place in Parsons B178 and the wind tunnel room. E80 students should already have card access to Parsons B178. If you cannot access the room, please contact Sue Lindley in the Engineering Department Office. 

You will be using COMSOL Multiphysics software Version 5.6 in this lab. You may practice using COMSOL and go through Granny Spark's COMSOL tutorials outside of your designated lab time. However, you CANNOT run COMSOL simulations on LAB-RELATED objects outside of your designated lab time.  These objects include the cylindrical objects tested in the wind tunnel, the NACA 6412 wing, your team's low-drag body, and your team's wing. 

This lab will be completed in full teams. It is up to the team to determine which parts of the lab are done by whom, and at what time during the 4 hours of lab time. 

Each team will have exactly 60 minutes to use the wind tunnel to run experiments and collect data.

The instructions for this lab are not detailed. You are expected to review the resources, plan out your experiments, and fill in the blanks.  

Not all deliverables are due at the end of lab this week. You will submit a submission sheet at the end of lab as a team (per usual), but each of you will write a technical memorandum about the team's process and findings individually. Details of the tech memo are discussed in the deliverables section below, but it is important to lay out the boundaries of collaboration on the tech memo. Specifically, the team must not collaborate on any writing in the tech memo at any time, and the team may not collaborate on the data or code after the assigned lab section is finished. 

**For pre-lab purposes**, a sample submission sheet that contains all of the questions and requirements on the submission sheet is[ here](https://docs.google.com/document/d/19XiX8GF38uZAgTSeCKnpc-Rh6QZxuwuRBFS4EH77MO0/edit?usp=sharing). 

By the end of the laboratory the student will:



1. Demonstration of the safe start-up and shut-down sequence for the wind tunnel.
2. Determination of wind speeds in the wind tunnel using a Pitot tube and digital manometer.
3. Measurement of drag forces on various shapes in the wind tunnel at various flow velocities.
4. Utilize COMSOL computational fluid dynamics (CFD) to model the drag and lift forces of the objects tested in the wind tunnel.
5. Compare the results obtained in the wind tunnel to those predicted by COMSOL.
6. Use COMSOL to create and simulate your own low-drag object and predict the drag forces that it will experience during service. 
7. Use COMSOL to create, simulate, and predict the lift and drag characteristics of a NACA 6412 wing. 
8. Use COMSOL to create, simulate, and predict the lift and drag characteristics of your own wing.

You will be provided with: 



* The HMC wind tunnel.
* A stainless steel Pitot tube (similar to the one shown[ here](https://dwyer-inst.com/series-160-stainless-steel-pitot-tube.html)).
* A Dwyer Series 475 Mark III Digital Manometer (click[ here](http://www.dwyer-inst.com/Product/Pressure/Manometers/Digital/Series475) for more information).
    * Note: Dwyer has released an app that you will find very useful. Search for "Dwyer Air Velocity Calculator" on Google Play or the App Store.
* A cylinder to be mounted in the wind tunnel.  These will be provided to you at the start of the lab, and you will measure their dimensions during lab.
* Three different nose shapes for the cylinder. These will be provided to you at the start of the lab, and you will measure their dimensions during lab.
* A computer with COMSOL in the Engineering Computing Facility (ECF). It is highly recommended that you practice using COMSOL in your pre-lab. Please see the links to the Grandma Spark's Step-By-Step guides and COMSOL tutorial videos mentioned below. You will not have time to learn COMSOL during lab.  

Here are informative resources on fluids, aerodynamics, and COMSOL that you should review PRIOR to lab:



* NASA Beginner's Guide to Aerodynamics (click[ here](https://www.grc.nasa.gov/www/k-12/airplane/short.html))
* E80 fluid measurements lecture notes (click[ here](https://drive.google.com/file/d/1R1AHWD5GR1xRkoNJdMfdgkJvw1xmn8XO/view?usp=sharing))
* Airfoil database (click[ here](http://www.airfoiltools.com/search/index?m%5Bgrp%5D=naca4d&m%5Bsort%5D=1))
* Airfoil and angle of attack definitions (click[ here](http://www.esru.strath.ac.uk/EandE/Web_sites/11-12/MORE/hydrofoil/img/1.jpg))
* NASA Wing geometry definitions (click[ here](https://www.grc.nasa.gov/www/k-12/airplane/geom.html)) 
* NASA Reynolds Number guide (click[ here](https://www.grc.nasa.gov/www/BGH/reynolds.html))
* Grandma Spark's step-by-step video guide to using COMSOL to model a cylinder in laminar flow (105 MB PowerPoint File, click[ here](https://drive.google.com/drive/folders/1llecHQqT-IsAfxxNEL-jZWsQFFYYczDG?usp=sharing))
    * Each slide on the PowerPoint contains a video!  Make sure that you press play on each video!
* Grandma Spark's step-by-step video guide to using COMSOL to model a NACA 0009 airfoil in laminar flow (164 MB PowerPoint File, click[ here](https://drive.google.com/drive/folders/1llecHQqT-IsAfxxNEL-jZWsQFFYYczDG?usp=sharing))
    * Each slide on the PowerPoint contains a video!  Make sure that you press play on each video!
* COMSOL video tutorials for beginners (click[ here](https://www.comsol.com/video/how-set-up-run-simulation-comsol-multiphysics))
* How to use COMSOL 3D geometry tools (click[ here](https://www.youtube.com/watch?v=1AggdrJzHyg))
* How to form unions in COMSOL (click[ here](https://www.youtube.com/watch?v=Q7fOawr58H0))
* Computing lift and drag forces in COMSOL (click[ here](https://www.comsol.com/blogs/how-do-i-compute-lift-and-drag/))

NOTE: The COMSOL CFD portion of this lab will consume most of your time in this lab.  You will not finish this lab if you are not prepared.  Reviewing the COMSOL resources above and practicing COMSOL ahead of time will be essential to your team's success in this lab. 

IMPORTANT SAFETY TIPS: For in-person labs



* Follow the dress code for E80 Lab.  Everyone must wear safety goggles during the test.  Hearing protection will be provided if needed.
* Never turn the fan on before checking to see that loose objects are NOT in the test chamber and the test chamber cover plate is secure.
* Ensure that all test personnel are at a safe distance from the wind tunnel itself (at least 24” in any direction).
* Make sure the article under test is securely fastened inside the test chamber.
* Never run the wind tunnel without a proctor or professor present.


## 1. Wind Tunnel Experiments

Your team will have exactly 60 minutes to complete this section. The order in which teams will conduct experiments in the wind tunnel will be randomly determined at the start of each section. Be ready to go first! If you are in a six-team section, you may be using the wind tunnel during the final hour of lab, and therefore you must have a plan in place to obtain data and submit your report by the deadline.


### 1.1 Getting to Know Your Wind Tunnel 

In this sub-section, you will familiarize yourself with the wind tunnel and relate airspeed to fan RPM.



1. A professor or proctor will take you to the wind tunnel room.
2. Locate the gray box that is the fan RPM controller for the wind tunnel.  Click[ here](http://www.eng.hmc.edu/NewE80/images/ControlPanel.jpg) to see what it looks like.
3. Locate the white box that displays the fan speed RPM.  Click[ here](https://drive.google.com/file/d/1Ca68NwGW_zSPMplpEriqC1aEvM0gSzak/view?usp=sharing) to see what it looks like.
4. Locate the LVDT box that displays lift and drag forces.  It is located above the wind tunnel test chamber.  Ensure that it is turned on.  If it is not, the switch is on the right side of the box in the rear.  DO NOT TOUCH THE KNOBS ON THE FRONT OF THIS BOX.  Click[ here](https://drive.google.com/file/d/0BzDxiDWHdPM6U21naVZSUGstU1k/view?usp=sharing&resourcekey=0-sotpLWHTgUCH_hEq54tl2w) to see what the box looks like.
5. Ensure that the fan is not running in the wind tunnel by pushing the "STOP" button.
6. Open the wind tunnel test chamber by removing the four clamps and gently removing the window.
7. Verify that there is nothing but a Pitot probe and the force measurement stand in the wind tunnel. If there are other objects in the wind tunnel, remove them.
8. Observe the mounting of the Pitot probe in the wind tunnel. Ensure that the end of the tube is properly oriented directly facing the incoming airflow. Ensure that the pitot probe is connected to the digital manometer.
9. Turn on the digital manometer. Zero it. To calculate air velocity, you can use this Excel spreadsheet[ PitotVelocityCalculator](https://docs.google.com/spreadsheets/d/1JXKPa2uhD6FO39ZgqziKAnF7XNatieHe/edit?usp=share_link&ouid=105511935419108795487&rtpof=true&sd=true) , this[ Google Sheet](https://docs.google.com/spreadsheets/d/1m22gxiGKOKdak-1UFEZurIgK5epST0CCiMBFQLzDiQM/copy?usp=sharing),  the Dwyer Air Velocity Calculator app or use the Dwyer Air Velocity Calculation Card that has been placed next to the wind tunnel. Use of these tools or the card requires that you know:
    * The ambient (room) temperature. Read the temperature sensor in the room.
    * The relative humidity. Read the humidity sensor in the room.
    * The absolute air pressure. Use a barometric pressure app on a cell phone. 
10. GENTLY push on the left side of the force measurement stand with one finger. What is happening to the drag force shown on the LVDT?  
11. GENTLY push on the right side of the force measurement stand with one finger. What is happening to the drag force shown on the LVDT?
12. GENTLY push on the top of the force measurement stand with one finger. What is happening to the drag force shown on the LVDT?
13. GENTLY pull on the top side of the force measurement stand with two fingers. What is happening to the lift force shown on the LVDT?  
14. Install the window on the test section and ensure that it is clamped at four corners. Make sure that everyone in the room is wearing safety goggles.
15. Power up the wind tunnel by pushing the green button labeled "START" on the gray box. You adjust the speed with the knob on the gray box. You read the RPM in the white box near the main power switch.  Measure the airspeed from 20% to 90% of max fan speed (in increments of 10%).  Allow time at each measurement for the wind tunnel to come to steady state. Repeat measurements with increasing and decreasing RPM to ensure reproducible results.  
16. Observe the lift and drag forces exhibited by the force measurement stand at each RPM setting.  How will these values be used in your calculations?
17. Plot a calibration curve of airspeed in the test section versus RPM. Perform the necessary regression analysis and display the appropriate error bars.
18. Zero the speed in the wind tunnel and push the red button labeled "STOP" on the gray box.


### 1.2 Measuring the Drag Forces on Cylindrical Objects

PLEASE BE GENTLE WHEN MOUNTING FIXTURES ONTO THE FORCE MEASUREMENT STAND.  IT IS A SENSITIVE PIECE OF EQUIPMENT.  DO NOT PUSH, PULL, PRESS DOWN, OR PULL UP WITH GREAT FORCE.  ASK FOR HELP FROM A PROCTOR OR PROFESSOR IF YOU NEED IT.  



1. When opening the wind tunnel, always ensure that there is no airflow by pressing the red "STOP" button and verifying that the fan RPM is zero.
2. Mount the cylindrical fixture on the force measurement stand and ensure that it is horizontal. Make sure that the side of the cylinder that says "FRONT TOWARDS FLOW" is actually facing the incoming flow.
3. Install "Nose #1" on the cylinder.
4. After ensuring that the window is securely clamped, power up the wind tunnel.
5. What values for lift and drag are shown on the LVDT box at zero flow velocity?  How will these values be used in your calculations?
6. Measure the drag force on the object from 20% to 90% of max fan speed (in increments of 10%).  
    * Using Excel, MATLAB, or other graphing software, plot a curve of Drag Force vs. Reynolds Number for Nose #1 (Do this in Parsons B178).  
    * Using Excel, MATLAB, or other graphing software, plot a curve of Drag Coefficient vs. Reynolds Number for Nose #1 (Do this in Parsons B178).  What are the correct reference area and characteristic length?
7. Bring the flow back down to zero and press the red "STOP" button, and then repeat steps 3-6 for "Nose #2" and "Nose #3".
    * Using Excel, MATLAB, or other graphing software, plot a curve of Drag Force vs. Reynolds Number for Nose #2 and for Nose #3 (Do this in Parsons B178).  
    * Using Excel, MATLAB, or other graphing software, plot a curve of Drag Coefficient vs. Reynolds Number for Nose #2 and for Nose #3 (Do this in Parsons B178).  What are the correct reference area and characteristic length? 


### 1.3 Measuring the Drag Forces on a Scale Robot Model 



1. When opening the wind tunnel, always ensure that there is no airflow by pressing the red "STOP" button and verifying that the fan RPM is zero.
2. Mount the 1/3 scale model of the robot in the wind tunnel chamber using a zip tie (as shown[ here](https://drive.google.com/open?id=1FAAhZU4SAByqlIppNAKiqhA1wdv5jFGf),[ here](https://drive.google.com/open?id=1MqhkhDmNm1tU7GKHu_Luwqd1PNU8G9d8) and[ here](https://drive.google.com/open?id=11Ly9iVza1-aJfTqkso-RaUQFSXsJPE67)). Pay attention to its orientation.  Ensure the window is securely clamped and power up the wind tunnel.
3. Record necessary calibration information, then record drag force on the object from 20%-90% of max fan speed (in increments of 10%).
    * Using Excel, MATLAB, or other graphing software, plot a curve of Drag Force vs. Reynolds Number for the scale model of the robot (Do this in Parsons B178).  
    * Using Excel, MATLAB, or other graphing software, plot a curve of Drag Coefficient vs. Reynolds Number for the scale model of the robot (Do this in Parsons B178).  What are the correct reference area and characteristic length? 


## 2. CFD Simulations of Cylindrical Objects

Make sure to download and watch Grandma Spark's step-by-step video guide to using COMSOL to model a cylinder in laminar flow (106 MB PowerPoint File, click[ here](https://docs.google.com/presentation/d/1e_maE5dcjPOEUGKOjZue8UUbkSufHgzy/edit?usp=sharing&ouid=100121681850908143159&rtpof=true&sd=true)).  Each slide on the PowerPoint contains a video. Make sure that you press play on each video. \




1. Use[ these dimensions](https://docs.google.com/presentation/d/1AQ0p3PNQByWXpu6GPy96D1zLtXJzXUER/edit?usp=share_link&ouid=105511935419108795487&rtpof=true&sd=true) of the objects that will be tested in the wind tunnel.  Note that the wind tunnel test section is 1 ft x 1 ft x 2 ft.
2. Perform COMSOL CFD simulations of your tests in the wind tunnel for the Cylindrical Object with Nose #1.   
    * Using Excel, MATLAB, or other graphing software, create a graph of Drag Force vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s).  How does drag force change with Reynolds Number?
    * Using Excel, MATLAB, or other graphing software, create a graph of Cd vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s). How does Cd change with Reynolds Number?
    * Create a velocity profile (single slice at centerline of body) for the 45 m/s flow condition. Grandma Sparks step-by-step guide shows you how to do this.
    * Create a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition. Grandma Sparks step-by-step guide shows you how to do this.
    * How do your computational results for drag and Cd compare to your experimental results? Were there any similarities or differences? What factors caused the differences?  Explain.
3. Perform COMSOL CFD simulations of your tests in the wind tunnel for the Cylindrical Object with Nose #2.  
    * Hint: An object can be rotated in COMSOL by selecting a Cartesian Axis and entering values for x, y, and z.
    * Using Excel, MATLAB, or other graphing software, create a graph of Drag Force vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s). How does drag force change with Reynolds Number?
    * Using Excel, MATLAB, or other graphing software, create a graph of Cd vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s). How does Cd change with Reynolds Number?
    * Create a velocity profile (single slice at centerline of body) for the 45 m/s flow condition.
    * Create a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition.
    * How do your computational results for drag and Cd compare to your experimental results? Were there any similarities or differences? What factors caused the differences? 
4. Perform COMSOL CFD simulations of your tests in the wind tunnel for the Cylindrical Object with Nose #3.  
    * Hint: An object can be rotated in COMSOL by selecting a Cartesian Axis and entering values for x, y, and z.
    * Using Excel, MATLAB, or other graphing software, create a graph of Drag Force vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s).  How does drag force change with Reynolds Number?
    * Using Excel, MATLAB, or other graphing software, create a graph of Cd vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s). How does Cd change with Reynolds Number?
    * Create a velocity profile (single slice at centerline of body) for the 45 m/s flow condition.
    * Create a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition.
    * How do your computational results for drag and Cd compare to your experimental results? Were there any similarities or differences? What factors caused the differences? 
5. Design an object using COMSOL that can achieve a LOWER Drag Coefficient than ALL of the cylindrical configurations that you have tested. Your team's object should have the same reference area as the cylindrical bodies that you have tested, and should have a minimum length that is no less than the cylindrical object with Nose #1, and a maximum length no more than the cylindrical object with Nose #3. 
    * HINT: If your object does not converge during the study, it is not possible for COMSOL to simulate it. Please re-design your object so that it converges during the study.  
    * Provide a detailed drawing of your object that shows relevant dimensions. 
    * Discuss the design process for your team's low-drag body. Why did you choose the dimensions and shape of your object?
    * Using Excel, MATLAB, or other graphing software, create a graph of Cd vs. Reynolds Number for air velocities between 5 m/s and 45 m/s (in increments of 10 m/s).
    * How does the performance of your team's low-drag object compare to the ones that you tested?  
    * Create a velocity profile (single slice at centerline of body) and a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition.
6. Use COMSOL to determine the drag forces that your custom cylindrical body will encounter when it is moving in water. COMSOL allows you to change the fluid in your simulations from air to water. However, changing the fluid to water alone is not enough. You need to use similitude to determine appropriate velocities in water. Use the concept of similitude to convert velocities in air between 5 m/s to 45 m/s to velocities in water. Once appropriate velocities in water are determined...
    * Plot the drag force vs. Reynolds Number for your cylindrical body in water.  
    * Plot the Cd vs. Reynolds Number for your cylindrical body in water.
7. Simulate a model of your robot (found[ here](https://drive.google.com/file/d/1S4ma0dsIwoG4uevQlVbE5IhP2XK05xuQ/view?usp=sharing)) in water at various velocities such that the Reynold's number is comparable to the Reynold's number of the scale model of the robot in the wind tunnel.  
    * Plot the drag force vs. Reynolds Number for your simulated robot
    * Plot the Cd vs. Reynolds Number for your simulated robot
    * Note that you're not expected to construct this model during the lab like the other shapes. The following instructions will help to do that
        * Select Model Wizard -> 3D -> Laminar Flow -> Stationary. Set units under the Geometry tab in the left hand column. 
        * Right click on "Geometry" in the left hand column and select "Import". When importing, make sure that under "Objects to import" both the "Solids" and "Surfaces" boxes are checked and that under "For surface objects:" you select "Form solids" (see[ photo](https://drive.google.com/open?id=16wiHEtWr8RCOmuXWEbpKF-HmT8qrxdqY)). 
        * Create the box and set up the laminar flow simulation as usual.


## 3. CFD Simulations of Wings

For parts 2 and 3 of this section, please make sure to watch  Grandma Spark's step-by-step video guide to using COMSOL to model a NACA 0009 airfoil in laminar flow (164 MB PowerPoint File, click[ here](https://docs.google.com/presentation/d/1KFulcloNJmJO0Bwzbz9RL0ppA24EBcsr/edit?usp=sharing&ouid=100121681850908143159&rtpof=true&sd=true)). Each slide on the PowerPoint contains a video. Make sure that you press play on each video.



1. Use these[ dimensions](https://docs.google.com/presentation/d/1TPHPbobRlIaPJLmFxf8QPqOL-NvRkuun/edit?usp=share_link&ouid=105511935419108795487&rtpof=true&sd=true) of a wing that COULD be tested in the wind tunnel. Note that the wind tunnel test section is 1 ft x 1 ft x 2 ft. What are the appropriate reference area and characteristic length to determine the lift force and coefficient of lift for the flat plate?  
2. Perform COMSOL CFD simulations of your tests in the wind tunnel for the "Flat Plate Wing". At three angles of attack (5, 15, and 45 degrees), vary the flow velocities between 5 m/s and 45 m/s.  
* Plot the lift force vs. Reynolds Number at each angle of attack at flow velocities between 5 m/s and 45 m/s (in increments of 10 m/s). Plot the three curves on the same axes so that you can compare your results.
    * Make sure that you indicate the angle of attack on each curve on the plot.  A legend or labels would be helpful!  
* Plot the coefficient of lift (Cl) vs. Reynolds Number at each angle of attack at flow velocities between 5 m/s and 45 m/s (in increments of 10 m/s). Plot the three curves on the same axes so that you can compare your results.
    * Make sure that you indicate the angle of attack on each curve on the plot. A legend or labels would be helpful!  
* Create a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition at a 15 degree angle of attack.
* How does the pressure on the bottom of the wing compare to the top of the wing at a 15 degree angle of attack?
1. Perform COMSOL CFD simulations of a wing based on the NACA 6412 airfoil that has a similar reference area as your flat plate at three angles of attack (5, 15, and 45 degrees).  Vary the flow velocities between 5 m/s and 45 m/s.
    * Plot the lift force vs. Reynolds Number at each angle of attack at flow velocities between 5 m/s and 45 m/s (in increments of 10 m/s). Plot the three curves on the same axes so that you can compare your results.
        * Make sure that you indicate the angle of attack on each curve on the plot. A legend or labels would be helpful!  
    * Plot Cl vs. Reynolds Number at each angle of attack at flow velocities between 5 m/s and 45 m/s (in increments of 10 m/s). Plot the three curves on the same axes so that you can compare your results.
        * Make sure that you indicate the angle of attack on each curve on the plot. A legend or labels would be helpful!
    * How does the NACA 6412 wing's Coefficient of Lift compare to the flat plate at an angle of attack of 15 degrees?
    * Create a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition at a 15 degree angle of attack.
    * How do the pressure differences between the top and bottom surfaces of the NACA 6412 wing compare to the pressure difference on the flat plate at 45 m/s and a 15 degree angle of attack?
2. Design a wing that will have a higher Cl than the flat plate and NACA 6412 wing at a chosen angle of attack (pick one: 5, 15, or 45 degrees), varying the flow velocities between 5 m/s and 45 m/s. Your wing must have the same reference area as the flat plate and NACA 6412 wing. You could either draw an airfoil in COMSOL and extrude it, plot it using points in the yz work plane followed by an extrusion, or any other method that your team chooses. This wing has to be unique to your team. You may use features of other airfoils in the airfoil database for inspiration, but you are not allowed to use any of the airfoils in the database.  
    * Provide a detailed drawing of your wing that shows relevant dimensions (e.g. chord line, camber line, max thickness, click[ here](http://www.esru.strath.ac.uk/EandE/Web_sites/11-12/MORE/hydrofoil/img/1.jpg) for details).
    * Plot the lift force vs. Reynolds Number at your chosen angle of attack for flow velocities between 5 m/s and 45 m/s (in increments of 10 m/s). Overlay the results of the flat plate and NACA 6412 wing at this angle of attack to compare the performance of the three wings.
        * Make sure that you indicate the chosen angle of attack on the plot. A legend or labels would be helpful!  
    * Plot the Cl vs. Reynolds Number at your chosen angle of attack for flow velocities between 5 m/s and 45 m/s (in increments of 10 m/s). Overlay the results of the flat plate and NACA 6412 wing at this angle of attack to compare the performance of the three wings.
        * Make sure that you indicate the chosen angle of attack on the plot. A legend or labels would be helpful!
    * How does your wing's Coefficient of Lift compare to the NACA 6412 wing and the flat plate at your chosen angle of attack?
    * Create a pressure contour plot (Contour Type: Filled) for the 45 m/s flow condition your chosen angle of attack.


## 4. Deliverables

For pre-lab purposes, a sample submission sheet that contains all of the questions and requirements on the submission sheet is[ here](https://docs.google.com/document/d/19XiX8GF38uZAgTSeCKnpc-Rh6QZxuwuRBFS4EH77MO0/edit?usp=sharing). 

Recall that no late work is accepted, we will grade whatever is submitted at the deadlines.

In addition, you will each individually submit a technical memorandum, which requires you to combine the writing skills that we have practiced in previous weeks in a longer format. Because the memorandum is longer, it is not due at the end of your lab week. Final report due date is 3/3/2023 for Group B and 3/10/2023 for Group A.Beware that the E72 final problem set has a due date that occasionally conflicts with this memo, so plan your time carefully. 

The memo will be written based on[ this prompt](https://drive.google.com/open?id=1x1NvKDmtAg4lXwxrBZ3tjtVtku8t3i0M), and we will do[ this activity](https://docs.google.com/presentation/d/1iyhcOw_lI1LpVT7DtUEsRWngSS-IUEgH/edit#slide=id.p1) during the writing and reflection (Friday, 2/24/2023 for Group B and Friday, 3/3/2023 for Group A) section of the week in which lab 6 is carried out. The activity won't take the whole section, so we encourage you to use the time to get started writing. When you have a draft, feel free to use this[ peer review worksheet](https://drive.google.com/open?id=1wpTIxQv4nZ6GcpaTAYyTMoLUzk0Jzemn) on your own time. We are grading on the criterion shown in[ this rubric](https://drive.google.com/open?id=1VCUnBQLSrwEUWhNtePDKEKU2eUPXrxt6), but we've left out the point breakdown because we want you to figure out what's important to emphasize on your own.

You are allowed to process your data any time until the report is due to write this report. If you are unable to generate results with your data in any section, then you may generate your own, simulated example data inside of MATLAB to analyze. You may not record any new data or run new COMSOL simulations. You may not share code, figures or text with any other students while writing this memo, though you may discuss ideas. We recommend that you make use of the writing center. Remember that you must submit a tech memo to pass the class.
