---
title: "Lab 6 Writing Assignment"
subtitle: Technical Memos
permalink: writing/lab6/index.html
---

## Writing Assignment

In this writing assignment you will write a complete technical memorandum about lab 6 that explains the experiments you undertook, your analysis, and your results.
This memo may be up to 5 pages long and should be in IEEE format.
Be sure to include an introduction that motivates the work and provides appropriate references, an introduction to the analytical models that you will use to check your data, a description of the experimental methods you use, reports of your data in figures and tables as appropriate, and a conclusion.
You have leeway in the organization of this work, and the scientific standard of Introduction, Background, Methods, Results, Conclusion may or may not serve you well depending on your approach.
Be sure to carefully select the appropriate topics to discuss so that your report fits in the page limit; the report won't have room to include every piece of data in the submission sheet. 

## Learning Objectives

By the end of this writing assignment you will...

- Learn to write a full technical report that follows the conventions of scientific writing.
- Reflect on and synthesize the skills that have been built through the previous writing assignments.

<!-- ## Required Resources

- [ ]  -->

## Specifications