---
title: "Lab 6 Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 

{{< pagebreak >}}
## Measured Calibration Curve for Wind Tunnel Fan Speed vs. Air Velocity

Effort:

- [ ] Present
- [ ] Includes zero speed calibration measurements

Complete:

- [ ] Discusses what to do with zero speed measurements. That transform is reflected in final calibration curve.
- [ ] Calibration curve shows correct numbers.
- [ ] Calibration curve shows correct regression line and uncertainty bounds.

{{< pagebreak >}}
## Plots of Drag Forces on Cylindrical Objects

This section calls for eighteen total graphs:

* Nose 1 measured drag force vs. Reynolds number.
* Nose 1 measured coefficient of drag vs. Reynolds number.
* Nose 1 simulated drag force vs. Reynolds number.
* Nose 1 simulated coefficient of drag vs. Reynolds number.
* Nose 1 simulated velocity profile.
* Nose 1 simulated pressure contour plot.
* Nose 2 measured drag force vs. Reynolds number.
* Nose 2 measured coefficient of drag vs. Reynolds number.
* Nose 2 simulated drag force vs. Reynolds number.
* Nose 2 simulated coefficient of drag vs. Reynolds number.
* Nose 2 simulated velocity profile.
* Nose 2 simulated pressure contour plot.
* Nose 3 measured drag force vs. Reynolds number.
* Nose 3 measured coefficient of drag vs. Reynolds number.
* Nose 3 simulated drag force vs. Reynolds number.
* Nose 3 simulated coefficient of drag vs. Reynolds number.
* Nose 3 simulated velocity profile.
* Nose 3 simulated pressure contour plot.

Effort:

- [ ] Graphs are present for at least one nose cone
- [ ] Calibration information, the zero fan speed lift and drag, is reported.
- [ ] Reference area used for finding drag coefficients is reported.

Complete:

- [ ] All plots show correct values.  
- [ ] Calibration information and reference area are correct.
- [ ] Discussion of differences between simulations and measurements lists plausible factors that could cause discrepancies.

{{< pagebreak >}}
## Plots of Drag Forces on Scale Robot Model

This section calls for four total graphs

* Measured drag force vs. Reynolds number
* Measured drag coefficient vs. Reynolds number
* Simulated drag force vs. Reynolds number
* Simulated drag coefficient vs. Reynolds number

Effort:

- [ ] All four graphs are present
- [ ] Calibration information, the zero fan speed lift and drag, is reported.
- [ ] Reference area used for finding drag coefficients is reported.

Complete:

- [ ] All plots show correct values.  
- [ ] Calibration information and reference area are correct.
- [ ] Discussion of differences between simulations and measurements lists plausible factors that could cause discrepancies.
- [ ] Explanation of how similitude lets us use a scale model of the robot in the wind tunnel and a full-sized model of the robot in simulated water flow.


{{< pagebreak >}}
## Plots of Lift and Drag for Flat Plate and NACA Airfoils at Different Angles of Attack

This section calls for six total graphs.

* Flat plate lift force vs. Reynolds number
* Flat plate coefficient of lift vs. Reynolds number
* Flat plate pressure contour plot
* NACA airfoil lift force vs. Reynolds number
* NACA airfoil coefficient of lift vs. Reynolds number
* NACA airfoil pressure contour plot vs. Reynolds number

Effort:

- [ ] The flat plate graphs are present.
- [ ] Includes a reference area and reference length for the flat plate measurements with one sentence of justification.

Complete:

- [ ] All plots are present.
- [ ] All performance numbers are reported
    *  Pressure on the bottom of the flat plate wing compare to the top of the flat plate wing at a 15 degree angle of attack
    * NACA 6412 wing’s Coefficient of Lift compared to the flat plate at an angle of attack of 15 degrees
    * Pressure differences between the top and bottom surfaces of the NACA 6412 wing compare to the pressure difference on the flat plate at 45 m/s and a 15 degree angle of attack
- [ ] Brief (4 sentence) discussion considering performance numbers and comparing NACA airfoil to flat plate wing.