---
title: "E80 Project: Field Deployment of an Autonomous Robot"
---

The final project for this class is deploying your AUV in open water in order to complete an experiment of your design.  This project offers many opportunities for creativity: there are a wide variety of interesting things in the ocean that can be measured. For example, environmental or scientific quantities (e.g., water quality, distribution of temperature, salinity, turbidity) and observation of marine life are good options, as are engineering properties such as sensor accuracy, battery life, sensor or craft mechanical durability, velocity vs. power, controller accuracy, or measuring the structural strains that large motors apply to the robots.  Get creative! We look forward to seeing what you come up with.

The minimum requirements of the project are as follows:

* Your robot must be autonomously deployed to take measurements without human intervention. 
* The deployment must last at least one minute and the robot must actively control its position during this minute.
* This deployment must end at a place where the robot can be recovered.
* Your sensor package must be deployed on or from your AUV, either in the water or in the air.
* Your sensor package must use at least three sensors with at least two unique electrical interfaces.
* The IMU, GPS, and motor current sensors that are already installed on the robot do not count towards this requirement, but they may be used as part of your data collection and analysis.
* Any sensors, including the ones you've installed or used as part of any of the labs, are fair game for this project. The extra-credit sections of labs and the [reference designs](/reference/design/) are a good source for sensors.

This project is structured as a set of cumulative deliverables which will help you gather data in time to complete the project. We track these deliverables by counting the weeks after spring break:

| Week | Activity                                         | Deliverable                                                                  |
|------|--------------------------------------------------|------------------------------------------------------------------------------|
|  1   | [Navigation Jump Start](/project/navigation)     | A graded [Submission Sheet](/project/navigation/submission.qmd). Submit on Canvas at end of your section |
|  2   | [Breadboard Demo](/project/build)                | An ungraded, but highly recommended, demo of breadboarded circuits to a prof | 
|  3   | [Soldered Protoboard Demo](/project/build)       | An ungraded, but highly recommended, demo of soldered circuits to a prof     | 
|  4   | [Deploy Integrated Robot](/project/field)        | None, though deployment during your section at Phake Lake is the first chance to get data for your report.   | 
|  5   | [Rebuild and Final Deployment](/project/field)   | None, though deployment *on Saturday* at Dana Point is the second and last chance to get data for your report. | 
|  6   | [Analyze Data](/project/report)                  | Rough draft of your report. Submit on Canvas on Friday                       |
|  7   | [Final Presentation and Report](/project/report) | Upload presentation slides and report to Canvas by 11:59PM the night before. |
__________
- **Saturday 4/20/2024**   <br>Relaunch at Dana Point<br>**ALL STUDENTS ARE EXPECTED TO ATTEND THE SATURDAY LAUNCH**

- **Wednesday 5/1/2024**   <br>**PROJECT PRESENTATION FOR ALL GROUPS**
