---
title: "Lab 3 Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 

Several of the deliverables in this submission sheet will call for schematics, oscilloscope traces or circuit pictures.  These are specific genres of technical documents, so they have conventions you need to adhere to.  The specifications for all schematics, oscilloscope traces and circuit pictures are listed on this page instead of being repeated for each deliverable in the document.

All schematics in this report should adhere the following specification:

- [ ] Include the stimulus for the circuit on the left
- [ ] Include power supply connections and bypass capacitors.
- [ ] Annotate each node with a name, using the name Vin for the input voltage and Vout for the measured output voltage
- [ ] Annotate each resistor and capacitor with a component value.
- [ ] Use implicit connections to connect the power supplies.
- [ ] Use the op-amp symbol to indicate operational amplifiers (instead of, e.g., a pinout diagram), but annotates that symbol with the chip used to make the op-amp.
- [ ] Represent op-amp circuits in their typical configurations, so that they look similar to videos.  Don't use non-typical drawings that make one type of op-amp circuit look like another.  (e.g.: don't draw a non-inverting amplifier with feedback on the top of the op-amp; that's usually how inverting amplifiers are drawn.)
- [ ] Generally keep signal flow left-to-right
- [ ] Generally keep high voltages at the top of the diagram and low voltages at the bottom.
- [ ] Space out components well enough and zoom in close enough that annotations are easy to read.
- [ ] Minimize unnecessary crossings, corners and jogs in the wires.  Use connect-by-name to reduce congestion among wires.  This [tutorial](https://learn.sparkfun.com/tutorials/how-to-read-a-schematic/reading-schematics) has more information.

All oscilloscope traces in this report should adhere to the following specification:

- [ ] Show each of the requested quantities on a separate oscilloscope channel.
- [ ] Scale the horizontal axis so 3-10 cycles of the input/output voltage waves are visible
- [ ] Scale the vertical axis to maximize size of the input/output waves without clipping
- [ ] Make sure the input/output waves use the same 0 V reference voltage.
- [ ] Be exported using the screen capture function of the oscilloscope.  Phone pictures of oscilloscope data are unacceptable.  (Note that in a normal lab setting it would be essential to also capture CSV output from the oscilloscope for later mathematical processing.  No need to do that in this lab, screen captures are fine.)

All pictures of circuits in this report should adhere to the following specification:

- [ ] Picture is taken at a level of lighting and zoom that allows a reader to trace connections in the circuit.
- [ ] The circuit is neatly laid out so that readers can trace connections in the circuit.

{{< pagebreak >}}
## Report on the Design and Characterization of a Non-Inverting Amplifier

Effort: 

- [ ] Provides a picture of the non-inverting amplifier
- [ ] Provides a schematic of the non-inverting amplifier and stimulus

Complete:

- [ ] Provides an oscilloscope trace of the input and the output for the following input: 100 mV amplitude sine wave with a 1 V offset.
- [ ] Provides an oscilloscope trace of the input and the output for the following input: 100 mV amplitude sine wave with a 0 V offset.
- [ ] Traces show correct behavior, matching designed gain and highlighting appropriate non-idealities
- [ ] Correctly, in 1-2 sentences, describes why the output signal in the 0 V offset trace does not fully obey the equation that describes non-inverting amplifier outputs.

{{< pagebreak >}}
## Report on the Design and Characterization of an Offset Amplifier

Effort:

- [ ] Provides a picture of the offset amplifier
- [ ] Provides a schematic of the offset amplifier

Complete: 

- [ ] Describes the design process for the offset amplifier: specifies the intended gain and offset, provides equation describing offset amplifier output Voltage, manipulates that equation (and states necessary assumptions) to find resistor values and showing the appropriate equation and hand calculations to find the  for offset amplifier output Voltage.
- [ ] Provides an oscilloscope trace of the input and the output for the following input: 100 mV amplitude sine wave with a 0 V offset.
- [ ] The output trace shows a complete sine wave with no op-amp introduced non-idealities.
- [ ] The op-amp trace behaves as predicted in the hand design.
- [ ] 1-2 sentences of discussion of why this design performs differently than a non-inverting amplifier for the same input.

{{< pagebreak >}}
## Report on the Design and Characterization of a 555 Timer LED Driver

Effort:

- [ ] Provides a picture of the 555 timer LED driver.
- [ ] Provides a schematic of the 555 timer LED driver.

Complete: 

- [ ] Provides an oscilloscope trace of the output, 555 capacitor node, and Voltage in the middle of the diode-resistor string.
- [ ] Trace indicates 500 Hz - 1 kHz operating frequency and ~60% duty cycle.
- [ ] Resistor value in schematic and resistor voltage measurement indicate diode is receiving 20-40 mA of current.
- [ ] Includes design process for 555 timer: lists target frequency and duty cycle, and shows how resistors and capacitors were selected to hit that target.
- [ ] Includes calculations showing how resistor was selected to limit current in IR1503.

{{< pagebreak >}}
## Report on the Design and Characterization of a Transimpedance Amplifier

Effort:

- [ ] Provides a picture of the transimpedance amplifier including the IR LED illuminating the photodiode
- [ ] Provides a schematic of the transimpedance amplifier

Complete: 

- [ ] Includes analysis of transimpedance amplifier circuit, showing relation between VOUT, ID and RF.
- [ ] Provides an oscilloscope trace of 555 timer output and transimpedance amplifier output when transimpedance photodiode is illuminated by the IR LED.

{{< pagebreak >}}
## Report on the Design and Characterization of a Turbidity Meter

Effort:

- [ ] Provides a picture of the prepared solutions in cuvettes.  Picture is annotated to indicate turbidity of each cuvette.
- [ ] Provides a picture of the assembled turbidity meter.

Complete: 

- [ ] Provides two sets of oscilloscope traces showing 555 timer output, 90° transimpedance amplifier output and transmission transimpedance amplifier output.  
  - The traces are gathered while a solution of middling turbidity is in the turbidity meter, so both 90° and transmission outputs are visible. 
  - The first set of traces are gathered under normal lighting conditions.
  - The second set of traces are gathered under shadowed lighting conditions.
- [ ] Plot of Vpp,90/Vpp,Transmission vs. Turbidity values annotated with uncertainty measures.
- [ ] Plotted turbidity data shows a linear relationship so measured Voltages can be used to predict turbidity.
- [ ] 2-3 sentences explaining why we use a switching LED, why we measure peak-peak Voltages in the transimpedance outputs, and why those decisions are related to ambient light.

{{< pagebreak >}}
## Extra Credit Writeups:

We don't provide complete specifications for extra credit writeups, but they will be graded for effort and completeness like normal sections.  You need to provide a "mini-report" of <1 page for each extra credit section that you attempt. Put a page break between each extra credit mini-report.