---
title: "History"
---

## 2018
A cleverly designed bottom crawler used powerful motors and a tethered surface skiff to map depth along accurate trajectories.  
https://drive.google.com/file/d/1s1zsGPTx-QZpVYCwWR4Md5jM4KVQRcAZ/view

An ASV used a particle filter based navigation and error correction system to achieve unusually good trajectory accuracy

https://drive.google.com/file/d/1hbRGmwnh3ZMJ5kYYFFD54oPrNAFauuVd/view


## 2017
An acoustic beacon tracker deployed in the Mudd test tank.  The oscillations in it's trajectory are characteristic of angle control based on stereo sensors, and the team had a MATLAB model which showed the same behavior.

https://drive.google.com/file/d/1nXRh81PjcI-u6L069lIfVtWcA4mYu-3c/view


A wind-measuring ASV did an exceptionally good job of sensor calibration, including using the wind tunnel to calibrate sensors.

https://drive.google.com/file/d/1RJtr_GxRZIaCJ95jLnJmj6HU9P30WT7T/view


## Older Versions of E80

E80 serves a critical role in the Harvey Mudd college curriculum and it's unsurprising that some of Mudd's best faculty have had ownership of the course.  A brief history of E80, courtesy of Erik Spjut on the previous E80 page, is provided below.   You can find the previous E80 website, a treasure trove of information, [here](http://www.eng.hmc.edu/NewE80/).

------------

**E80, Hammer Time **was one of the most successful field laboratory courses of all time. Zee Duron is widely acknowledged as one of the premiere course directors of the 21st Century. But time moves on, fashions change, and people move to other projects. Duron has moved on to administrative work, and he has left **E80, The Next Generation **to [Erik Spjut](http://www.eng.hmc.edu/EngWebsite/index.php?page=DisplayPerson.php&personID=15) and [Mary Cardenas](http://www.eng.hmc.edu/EngWebsite/index.php?page=DisplayPerson.php&personID=20). The challenges and expectations of this sequel are chronicled in this website. We invite you to explore and enjoy.


### The Harvey Mudd Way

A key element of the philosophy of the Harvey Mudd College General Engineering education is that there are fundamental principles that are applicable to many engineering disciplines. Experimental Engineering (E80) is a sophomore-level, semester-long required course, which has striven to teach a large subset of these fundamental principles through multiple experiments in a number of engineering disciplines. We are redesigning the Experimental Engineering course to explicitly require learning in multiple engineering disciplines while directing all of the experiments to a final goal: to build, instrument, and fly a small rocket; and analyze and report on the data collected during the flight.

The project involves the creation of learning materials, teaching strategies, and equipment for a multidisciplinary experimental engineering course involving the instrumentation and testing of these small model rockets. The project includes the design, acquisition, and testing all of the pedagogy, hardware, and software necessary to implement the revised course. We will conduct the course several times with formal assessment, revise the course in response to that assessment, and distribute the course plans, instrumentation requirements, and pedagogical results to the wider academic community. Our plans and results will be presented on this web site.


### The Wider World

It is difficult to predict where the commercial space era will take us, but this project will fulfill a need for multidisciplinary engineers interested in aerospace applications. The pedagogical materials can be used at a number of engineering institutions to teach experimental engineering in a multidisciplinary way, not only to the students, but also to faculty (at HMC and other institutions) who may not have industrial or hands-on multidisciplinary engineering experience. The proposed learning workshop for faculty will be a means for disseminating the creative learning materials and teaching strategies. Outreach to local middle schools will introduce rocketry (and the associated mathematics and physics) to a very diverse population; there is a real opportunity to increase the interest in and pursuit of math, science, and engineering by these diverse groups, and to increase the diverse and properly-trained workforce in these areas.
