---
title: Lab 1 Prelab Help Sheet
number-sections: true
---

Here are some ideas of useful prelab activities.  There are a lot, so it makes sense to apportion them among your team.  However, some activities (watching lecture videos, reading) should be completed by everyone. Be careful not to break up work too strictly, because many of the topics covered by the lab stretch across these prelab divisions; it makes sense to read carefully and try to identify linked problems and work before breaking up the tasks, and it makes sense to share individual findings thoroughly with the group.  

## Reading and Reference

- [ ] Watch lecture videos.
- [ ] Read the lab.
- [ ] Flag parts of the lab that didn't make sense for discussion with your team or a prof.
- [ ] Read the submission sheet and notice:
  1. What are the deliverables? 
  2. What are the specifications on those deliverables?
- [ ] Read the motherboard manual.
- [ ] Read the motherboard assembly guide.
- [ ] Read and answer all of the safety questions.
- [ ] Read the lab overview and note safety procedures and appropriate attire.

## Software

- [ ] Double check that the E80 Git repo is available and working.
- [ ] Test compile `E80_Lab_01.ino`.
- [ ] Write a version of `E80_Lab_01.ino` for testing motors and test compile it.
- [ ] Write a version of `E80_lab_01.ino` for running the obstacle course and test compile it.
- [ ] Import the sample `INF` and `BIN` file data using `logreader.m`.
- [ ] Write software that will generate acceleation plots in Matlab based on the `logreader.m` sample data.

## Statistics

- [ ] Write code to find the mean of a dataset in Matlab.
- [ ] Write code to find the standard deviation of a dataset in Matlab.
- [ ] Write code to conduct a T-test for two datasets in Matlab.
- [ ] Make sure you understand the math behind means and standard deviations.
- [ ] Make sure you understand the math behind T tests (which isn't in the videos so you may have to dig through old notes or the internet).

## Mechanical

- [ ] Read all the robot assembly instructions.  Verify that you understand:
  1. Box modifications 
  2. Drill hole locations
  3. Drilling procedures
  4. Penetrator assembly (are you clear on the parts of the bolt, the gasket?)
  5. Mounting the box on the frame 
- [ ] Make some sketches of how you expect the robot to look during various parts of the assembly process (and how it is changing relative to E79) to test your understanding.
- [ ] What do you expect the buoyant force of your robot to be?
- [ ] What ballast mass will make your robot neutrally buoyant?
- [ ] How many ballast plates do you think that will take?
- [ ] What tools do I have to measure masses in lab anyway?

## Results and E79 Theory

- [ ] Make a plan for how your team will split its time in lab.
- [ ] How are you going to find the size of one accelerometer unit?  Can you write software (or a spreadsheet) to do that?
- [ ] Manipulate the E79 equation so it predicts peak acceleration from rest.
- [ ] What shape do you expect for an acceleration curve produced by the E79  governing equation after a step in thrust?  How might it get messed up in the real world?
- [ ] Write up the math parts of your submission sheet so that you can just paste in results in lab.