---
title: "Lab 1 Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 

## Provide acceleration plots and analysis

This submission item will cover multiple questions from the "Motherboard Validation, IMU Calibration, and IMU Error Measurement" section:  

- How many m/s^2 does one accelerometer unit represent?
- What are the x, y and z axis zero acceleration measurements?
- Are the x, y and z axis zero acceleration measurements statistically different from one another?
- What are the mean, standard deviation, standard error and 95% confidence bounds for a static acceleration measurement in the z direction?

Answering these questions requires data from your accelerometer, which you should include in this submission as three graphs depicting data from the same trial, one showing x acceleration, one showing y acceleration, and one depicting z acceleration.

Effort Specification:

- [ ] Includes four plots of data from the accelerometer that show zero acceleration x data, zero acceleration y data, zero acceleration z data, and z data that reflects acceleration due to gravity.
- [ ] Plots are labeled (in title or caption) to indicate which is zero x, zero y, zero z and accelerated z.
- [ ] Accelrated z plot has different mean from other plots.
- [ ] Vertical scale is set to show variations in the data values.
- [ ] Y-axis is set so we can easily read off values.
- [ ] Includes some calculations for each question.

Complete Specification:

- [ ] Calcuations that relate acceleration due to gravity to one accelerometer unit are correct.
- [ ] Take the mean of data to calculate the resting zero acceleration values. Report them clearly with appropriate uncertainty bounds.
- [ ] Includes description of how to calculate statistics and correct values.
- [ ] Includes description of how to calculate T tests and results of tests on data.

{{< pagebreak >}}
## Paste the code used to navigate the obstacle course

Effort Specification:

- [ ] Present and reasonable.

There is no complete specification for this deliverable.

{{< pagebreak >}}
## Plot acceleration measurements vs. the sample number from a run in the obstacle course.  (No need to convert the x-axis to time.)

Effort Specification:

- [ ] Present and interpretable.

Complete Specification:

- [ ] Shows multiple acceleration events that suggest motion through an obstacle course.  
- [ ] Scale is legible and data is cropped to just the run through the obstacle course, omitting getting the robot into the tank, fishing it out, etc.

{{< pagebreak >}}
## Write a formula for peak acceleration of a robot from rest, calculate the predicted acceleration that formula makes, and compare that value to the peak acceleration observed in your measurements.

Effort Specification:

- [ ] Appropriate governing equation copied from E79 notes.
- [ ] Equation manipulated into a form that predicts peak acceleration from rest.

Complete Specification:

- [ ] Manipulated equation is fully correct and well explained.
- [ ] Annotation of the obstacle course acceleration plots show the measured peak acceleration from rest.
- [ ] Theoretical numbers for thrust extracted from E79 resources.
- [ ] Thrust and mass are used to predict theoretical peak acceleration.
- [ ] Comment on differences between theory and measurement.

