---
title: "Project Jump Start Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 


{{< pagebreak >}}
## Include Code Modifications to Implement New Printer Functionality

Effort: 

- [ ] Includes modified code from the `PrintRollPitchHeading()` function from `SensorIMU.cpp`.
- [ ] Includes modified printer `if` statement from the main loop of `E80_Lab_07_dive.ino`.  (Approximately lines 107-121.)
- [ ] Includes an estimate of your main loop sampling frequency derived by looking up `LOOP_PERIOD` in `TimingOffsets.h`.

Complete:

- [ ] Loop period estimate is correct.

{{< pagebreak >}}
## Graphs of Position Inferred from IMU

Effort: 

- [ ] Includes plot of x,y coordinates of board stack overlaid on ideal 0.5 m path.  X-axis should be x coordinate in meters.  Y-axis should be y coordinate in meters.  Plot includes appropriate axis labels and units.
- [ ] Includes plot of y coordinate of board stack vs. time (you can figure it out from sample number and the loop period from earlier sections) with uncertainty bounds derived from theory of integrating noisy accelerometer data.

Complete:

- [ ] x, y coordinates do not resemble 0.5 m path because of accumulated noise.
- [ ] y coordinate vs. time remains within theoretical bounds.

{{< pagebreak >}}
## Dive Activity Only: Pressure Calibration Curve

Effort: 

- [ ] Includes plot of depth vs. Teensy reported Voltage with at least 7 points.  Plot includes line of best fit and uncertainty bounds on fit.
- [ ] Includes updated `depthCal_slope` and `depthCal_intercept` values.

Complete:

- There are no complete requirements for this section.

{{< pagebreak >}}
## Dive Activity Only: Control Effort and Trajectory from Deployment

Effort: 

- [ ] Includes modified code from the `dive()` function from `DepthControl.cpp`.
- [ ] Includes plot of `depth` and `depth_des`, overlaid on the same y-axis vs. time on the x-axis. Includes appropriate labels, units and legends.
- [ ] Includes plot of `uV` vs. time with appropriate labels and units.  You have the option of including this as an x-aligned subplot below the `depth`/`depth_des` plot, which highlights how effort is related to the robot's depth.

Complete:

- [ ] `depth` tracks `depth_des`, `uV` decays as `depth` approaches `depth_des`, and system exhibits the second-order settling characteristic of P-control on depth in a robot.

{{< pagebreak >}}
## Surface Activity Only: Calibrated and Uncalibrated Magnetometer Performance

Effort: 

- [ ] Includes figure generated by `Mag_Calibration.m`. 
- [ ] Includes figure of superimposed calibrated and uncalibrated magnetometer amgentic induction measurements (in mG) on xy plane. 
- [ ] Includes figure of superimposed calibrated and uncalibrated heading (in radians) vs. time measurements. 

Complete:

- There are no complete requirements for this section.

{{< pagebreak >}}
## Surface Activity Only: GPS Points from Walking a Path

4.2 Plot the logged x,y positions from the path you walked with your GPS


Effort: 

- [ ] Includes modified code from the `updateState()` function from `XYStateEstimator.cpp`.  This function should calculate `state.x`, `state.y` and `state.yaw` (by converting from heading).
- [ ] Includes a plot of measured x and y positions during the walk around Parsons. The x-axis should be the x coordinate, and the y axis should be the y coordinate. Overlay this plot on an image of campus to effectively show the path.

Complete:

- There are no complete requirements for this section.

{{< pagebreak >}}
## Surface Activity Only: Control Effort and Trajectory from Deployment

Effort: 

- [ ] Includes plot of logged paths of x,y points overlaid on ideal trajectory and an image of campus.  X-axis is x measurement in meters.  Y axis is y measurement in meters.
- [ ] Includes plot of angle error vs. time.
- [ ] Includes plot of control effort vs. time. You have the option of including this as an x-aligned subplot below the angle error plot, which highlights how effort is related to the robot's heading.

Complete:

- There are no complete requirements for this section.




