---
title: "Lab 4 Writing Assignment"
subtitle: Introductions
permalink: writing/lab4/index.html
---

## Writing Assignment

In this writing assignment you will learn to write an introduction to a technical memo or lab report.
Introductions serve several purposes:

1. State relevant background information about the completed work to put it in context. Prior work must be properly referenced and cited.
2. Briefly communicate the remaining content of the report.

## Learning Objectives

By the end of this writing assignment you will...

- Write a 2-3 paragraph introduction to provide the context for your experiment
- Create a bibliography with properly formatted references.

<!-- ## Required Resources

- [ ]  -->

## Specifications

### Lab Report Introduction 

- [ ] Provides pertinent information about the scientific concept (theory, model, principle, procedure) that motivates your experiments.
- [ ] Presents the purpose of your experiment and discusses why it is important to E80 students.
- [ ] Explains why you selected the specific models to compare against your experiments.
- [ ] States a hypothesis for each experiment and explains the scientific reasoning that leads to the hypothesis.
- [ ] Describes the forthcoming sections of the lab report, which demonstrates a well-planned report organization.


### References

- [ ]	Refer to appropriate sources, primarily peer reviewed articles and texts that are related to the lab.
- [ ]	Uses the standard IEEE article format for citations and references.
- [ ]	References are used appropriately: often enough to support every contentious point, but not so often as to be pedantic.

### Text

- [ ] Correct sentence mechanics like cohesion and coherence between sentences and no run-ons
- [ ] Correct paragraph mechanics like topic sentences and placement at breaks between ideas
- [ ] Language is not stilted and jargon is kept to a reasonable minimum.

### Technical Inferences in Text

- [ ] Different temperature measurement techniques have very different speeds.
- [ ] Different temperature measurements have different degrees of decoding complexity.
- [ ] Both of the above are backed up with appropriate references.
