---
title: "Lab 4 Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 

Several of the deliverables in this submission sheet will call for schematics, oscilloscope traces or circuit pictures.  These are specific genres of technical documents, so they have conventions you need to adhere to.  The specifications for all schematics, oscilloscope traces and circuit pictures are listed on this page instead of being repeated for each deliverable in the document.

All schematics in this report should adhere the following specification:

- [ ] Include the stimulus for the circuit on the left
- [ ] Include power supply connections and bypass capacitors.
- [ ] Annotate each node with a name, using the name Vin for the input voltage and Vout for the measured output voltage
- [ ] Annotate each resistor and capacitor with a component value.
- [ ] Use implicit connections to connect the power supplies.
- [ ] Use the op-amp symbol to indicate operational amplifiers (instead of, e.g., a pinout diagram), but annotates that symbol with the chip used to make the op-amp.
- [ ] Represent op-amp circuits in their typical configurations, so that they look similar to videos.  Don't use non-typical drawings that make one type of op-amp circuit look like another.  (e.g.: don't draw a non-inverting amplifier with feedback on the top of the op-amp; that's usually how inverting amplifiers are drawn.)
- [ ] Generally keep signal flow left-to-right
- [ ] Generally keep high voltages at the top of the diagram and low voltages at the bottom.
- [ ] Space out components well enough and zoom in close enough that annotations are easy to read.
- [ ] Minimize unnecessary crossings, corners and jogs in the wires.  Use connect-by-name to reduce congestion among wires.  This [tutorial](https://learn.sparkfun.com/tutorials/how-to-read-a-schematic/reading-schematics) has more information.

All pictures of circuits in this report should adhere to the following specification:

- [ ] Picture is taken at a level of lighting and zoom that allows a reader to trace connections in the circuit.
- [ ] The circuit is neatly laid out so that readers can trace connections in the circuit.

{{< pagebreak >}}
## Report on the Design and Characterization of a Pressure Sensor Interface Circuit

Effort: 

- [ ] Provides a picture of the pressure sensor interface circuit, including the pressure sensor
- [ ] Provides a schematic of the pressure sensor interface circuit, including the pressure sensor
- [ ] Equation relating depth to pressure sensor output Voltage is included.
- [ ] Equation relating op-amp input Voltage to op-amp output Voltage is included.  May be incorrect if it looks like a good faith effort.

Complete:

- [ ] Equation relating op-amp input to op-amp output is correct.
- [ ] Equations are combined into an overall equation relating depth and op-amp output Voltage.
- [ ] Provides a table of results that matches the form below with at least five data points.  Note the following: 
  - VOP is predicted output Voltage
  - $\lambda$V is uncertainty in predicted output Voltage
  - VOM is measured output Voltage 
  - $\lambda$M is uncertainty in measured output Voltage
  - ERR is error between prediction and measurement
- [ ] A graph of a calibration curve between pressure and depth is provided.  The data points match the points in the table below.  Appropriate regressions and measures of uncertainty are plotted.
- [ ] Predicted and measured Voltages match to within uncertainty and are consistent with equations.
- [ ] Predicted and measured Voltage at 0 m depth is close to 0.3 V or 3.0 V.
- [ ] Predicted and measured Voltage at 40 cm depth is close to 0.3 V or 3.0 V (whichever is farthest from the 0 m measurement)

| Depth (cm) | VOP (V) | $\lambda$V (V) | VOM (V) | $\lambda$M (V) | ERR (%) | 
| -----------|---------|----------------|---------|----------------|---------|
|   0        |         |                |         |                |         |
|   ...      |         |                |         |                |         |

{{< pagebreak >}}
## Report on the Design and Characterization of a Thermistor Interface Circuit

Effort: 

- [ ] Provides a picture of the thermistor interface circuit, including the thermistor divider.
- [ ] Provides a schematic of the thermistor interface circuit, including the thermistor divider.
- [ ] Equation relating op-amp input Voltage to op-amp output Voltage is included.  May be incorrect if it looks like a good faith effort.

Complete:

- [ ] Equation relating op-amp input to op-amp output is correct.
- [ ] Predicted and measured resistance values are reported with uncertainty for 0 °C and 20 °C temperatures.
- [ ] Predicted and measured output voltages are reported with uncertainty for 0 °C and 20 °C temperatures.
- [ ] Predicted Voltages and measured voltages match to within uncertainty and are consistent with equations.
- [ ] Predicted and measured Voltage at 0 °C is close to 0.3 V or 3.0 V.
- [ ] Predicted and measured Voltage at 20 °C is close to 0.3V or 3.0 V (whichever is farthest from the 0 °C measurement).

{{< pagebreak >}}
## Report on Steinhart-Hart Fitting of Thermistor

Provide a table of results that matches the form below.  Note the following: 
- T is the temperature measured by the digital thermometer
- $\lambda$T is uncertainty in T.
- R is the resistance measured by the multimeter.
- $\lambda$R is uncertainty in R.

Also provide extracted Steinhart-Hart coefficients with uncertainty and two graphs.  One graph overlays R-T data, the Steinhart-Hart fit and the fit from the datasheet.  The other provides residuals from the Steinhart-Hart fit.

Effort:

- [ ] At least four of table rows are filled in.  May omit uncertainty columns.
- [ ] Provides graph of 1/T vs. R data.

Complete: 

- [ ] All table rows are filled in.
- [ ] All uncertainties are included and correct.
- [ ] Includes code showing how to calculate Steinhart-Hart coefficients.
- [ ] Includes a plot of 1/T vs. R that shows measured points with uncertainty, fit based on datasheet equation, and fit based on extracted Steinhart-Hart coefficients.
- [ ] Include plot of residuals from Steinhart-Hart fit.

| T (°C) | $\lambda$T (°C) | R (k$\Omega$) | $\lambda$R (k$\Omega$) |
|--------|-----------------|---------------|------------------------|
|        |                 |               |                        |
|        |                 |               |                        |
|        |                 |               |                        |

{{< pagebreak >}}
## Report on Measurements of Thermocouple

Provide a table of results that matches the form below.  Note the following: 
- TT is the temperature measured by the digital thermometer
- $\lambda$T is uncertainty in TT.
- TK is the temperature measured by the type-K thermocouple when the multimeter was in temperature mode.
- $\lambda$K is uncertainty in TK.
- V is the thermocouple Voltage when the multimeter was in Voltage mode.
- $\lambda$V is the uncertainty in V.
- CJC is the cold junction compensation Voltage.
- TD is the temperature decoded from the Voltage in Thermocouple mode. 
- $\lambda$D is the uncertainty in TD.

Effort:

- [ ] At least two of table rows are filled in.  May omit uncertainty columns.
- [ ] CJC column has at least a reasonable guess.

Complete: 

- [ ] All table rows are filled in.
- [ ] All uncertainties are included and correct.
- [ ] CJC column and decoded temperature are correct for measured Voltages.

| TT (°C) | $\lambda$T (°C) | TK (°C) | $\lambda$K (°C) | V (mV) | $\lambda$V (mV) | CJC (mV) | TD (°C) | $\lambda$D (°C) |
|---------|-----------------|---------|-----------------|--------|-----------------|----------|---------|-----------------|
|         |                 |         |                 |        |                 |          |         |                 |
|         |                 |         |                 |        |                 |          |         |                 |
|         |                 |         |                 |        |                 |          |         |                 |

{{< pagebreak >}}
## Report on Settling Times of Temperature Sensors

Effort:

- [ ] Includes picture of all three sensors next to measurement setup.
- [ ] Reports three settling times, one for each sensor.

Complete: 

- [ ] Settling times are consistent with results from lecture.
- [ ] Brief (3-5 sentence) discussion about which sensors are appropriate for E80 robots and for cold-junction compensation sensors.

{{< pagebreak >}}
## Extra Credit Writeups:

We don't provide complete specifications for extra credit writeups, but they will be graded for effort and completeness like normal sections.  You need to provide a "mini-report" of <1 page for each extra credit section that you attempt. Put a page break between each extra credit mini-report.
