---
title: "Lab 4 Writing Assignment"
subtitle: Introductions
---

## Writing Assignment

In this writing assignment you will learn to write an introduction to a technical memo or lab report.
Introductions serve several purposes:

1. State relevant background information about the completed work to put it in context. Prior work must be properly referenced and cited.
2. Briefly communicate the remaining content of the report.

## Statement of Work

Prepare a 400-500 word introduction section based on the temperature sensors used in Lab 4.
Your writeup should introduce the topic of temperature measurement and describe the three different measurement devices discussed in Lab 4: thermistors, active linear temperature sensors, and thermocouples.
The introduction should provide an overview and motivation of temperature sensing along with a description of desired properties of an effective temperature sensing device.
It should also include background information on each of these sensors along with citations to appropriate sources in IEEE format as needed to back up any claims.
See the [references section](#references) below for more information on how to correctly format the citations.

If you were writing a full report (like you will in Lab 6), your introduction would also contain a paragraph at the end to explain the remaining content of the report as if you were writing it. 
You do not need to include this paragraph for your writing assignment this week, but we've provided you with some sample text below that you can adapt when writing your Lab 6 technical memo.

"The remainder of this report will present the methods used to carry out the experiments and measurements. The methods section will describe how the temperature measurement devices were constructed and the circuits used to interface them to the measurement equipment. Then, the results section will present data demonstrating the relative response times of the three different temperature measurement schemes. The report will conclude by addressing potential areas for future work and the limits of the existing experiments."

## Learning Objectives

By the end of this writing assignment you will...

- Write an introduction to provide the context for your experiment.
- Create a bibliography with properly formatted references.

## Required Resources

- [ ] Lab 4 assignment

## Specifications

### Effort

- [ ] Introduction describes all three temperature sensors.
- [ ] Introduction presents some references to support claims.
- [ ] References are included even if formatting is incomplete.

### Completion

#### Lab Report Introduction 

- [ ] Provides pertinent information about the scientific concept (theory, model, principle, procedure) that motivates your experiments.
- [ ] Presents the purpose of your experiment and discusses why it is important to E80 students.
- [ ] Explains why you selected the specific models to compare against your experiments.
- [ ] States a hypothesis for the respective response times of the three temperature sensors and explains the scientific reasoning that leads to the hypothesis.

#### References

- [ ]	Refer to appropriate sources, primarily peer reviewed articles and texts that are related to the lab.
- [ ]	Uses the standard IEEE article format for citations and references.
- [ ]	References are used appropriately: often enough to support every contentious point, but not so often as to be pedantic.

#### Text

- [ ] Correct sentence mechanics like cohesion and coherence between sentences and no run-ons.
- [ ] Correct paragraph mechanics like topic sentences and placement at breaks between ideas.
- [ ] Language is not stilted and jargon is kept to a reasonable minimum.

#### Technical Inferences in Text

- [ ] Different temperature measurement techniques have very different speeds.
- [ ] Different temperature measurements have different degrees of decoding complexity.
- [ ] Both of the above are backed up with appropriate references.

## References  {#sec-references}

Providing appropriate references for your work is critical.
There are a variety of different reference styles.
You may be familiar with some popular ones from your humanities classes like MLA and APA.
There are also many different scientific citation styles, each with their own pros and cons.
In this lab, we will use IEEE citation style which is a concise and clear way of listing references.

In the IEEE style, references are listed in the bibliography in citation order and are indicated in the text with the corresponding reference number in square brackets (e.g., [2]).
Each reference in the bibliography should include:

1. The author’s name listed as first initial of first name, then the full last name.
2. The title of article, patent, conference paper, etc., in quotation marks.
3. The title of the journal or book from which the reference is taken in italics.


The short guide from IEEE available [here](./assets/IEEE%20Citation%20Guidelines.pdf) has a list of helpful examples for you to follow (e.g., how to cite a datasheet).

While there are many tools like [Zotero](https://www.zotero.org) or [Mendeley](https://www.mendeley.com) which can help you manage your research library and automatically generate citations, these are most useful once you are dealing with a large number of references.
You are welcome to use these tools for this writeup if you wish, but it will likely take more time to set up and wrangle with the tool than it would to manually format the references yourself by hand.
For this lab, we recommend that you write the references without the aid of a reference manager so that you can understand the main components of a reference.
Whether you use a tool or not, you should always double check your citations to make sure they are complete and accurate.