---
title: "Lab 2 Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 

## What is one 'Teensy Unit'? 

i.e.: How much has the Voltage input to the Teensy changed when the number reported by `matlablogging.m` increases by 1?  Include a graph of Teensy output vs. sample number, any other relevant information about your test setup or measurements, and calculations showing how you did your conversion from Voltage to Teensy units.

Effort Specification:

- [ ] Includes a graph of data sampled from the Teensy
- [ ] Includes information (an oscilloscope measurement, a multimeter measurement, or a detail of how the function generator is set up) that can be used to calibrate the vertical scale of the Teensy graph.
- [ ] Some calculations present

Complete Specification:

- [ ] One sentence describing what happens to Teensy outputs when Teensy inputs are less than zero
- [ ] One sentence explaining what point or points were used to calculate the Teensy unit.
- [ ] Calculations are correct and yield the proper Teensy unit value.  

{{< pagebreak >}}
## What is the sample rate of the Teensy running matlablogging.ino? 

Effort Specification:

- [ ] Includes a graph of data sampled from the Teensy
- [ ] Includes information (an oscilloscope measurement or a detail of how the function generator is set up) that can be used to calibrate the horizontal scale of the Teensy graph.
- [ ] Some calculations present

Complete Specification:

- [ ] Calculations are correct and yield the proper Teensy unit value.
- [ ] Results are used to explain measurement errors that are present in the 175 kHz measurement that are not present in the 200 Hz measurement.

{{< pagebreak >}}
## Fill in this table of properties for voltage dividers

Fill in only one of the "Measured Output Voltage" columns for each measurement, whichever is appropriate to the instrument that you are using to measure.  If you are using the "Measured Output Voltage (Vpp)" column, then also convert that measured voltage to an RMS value in the "Converted Output Voltage (Vrms)" column.

Several column names have been abbreviated to make that table easier to fit on one page:

- VOPI refers to "Predicted output Voltage with ideal components", which is the prediction you are able to make before the start of lab.
- VOPC refers to "Prediction output Voltage with measured components", which refers to predictions of the output voltage that you make once you have measured your exact component values in lab.
- VOM refers to "Measured output voltage".  There are two VOM columns, one in units of Vrms, and the other in units of Vpp.  Fill in only the column appropriate to the instrument you are using.
- VOC refers to "Converted output voltage".  This column will only be filled in for VOM measurements that use the Vpp units.  It should contain the RMS Voltage that corresponds to your measured peak-peak Voltage.
- $\lambda$ refers to the 95% confidence bounds you predicted for VOPI.
- ERRI refers to the percent error between your VOPI and VOM/VOC.
- ERRC refers to the percent error between your VOPC and VOM/VOC.

Provide example calculations showing how you calculated the predicted output voltage and the predicted uncertainty bounds of the case where Z1=10 M$\Omega$, Z2=20 M$\Omega$ and you measured the output with the multimeter.

| Z1 & Z2 | Instrument | VOPI (Vrms) | VOPC (Vrms) | VOM (Vrms) | VOM (Vpp) | VOC (Vrms) | $\lambda$ (V) | ERRI (%) | ERRC (%) |
|---------|------------|-------------|-------------|------------|-----------|------------|---------------|----------|----------|
| Z1=wire Z2=open | Multimeter | | | | | | | | 
| Z1=wire Z2=open | 1x Scope Probe | | | | | | | | 
| Z1=wire Z2=open | 10x Scope Probe | | | | | | | | 
| Z1=wire Z2=open | Teensy | | | | | | | | 
| Z1=10 $\Omega$ Z2=20 $\Omega$ | Multimeter | | | | | | | |
| Z1=10 $\Omega$ Z2=20 $\Omega$ | Teensy | | | | | | | |
| Z1=1 k$\Omega$ Z2=2 k$\Omega$ | Multimeter | | | | | | | |
| Z1=1 k$\Omega$ Z2=2 k$\Omega$ | Teensy | | | | | | | |
| Z1=100 k$\Omega$ Z2=200 k$\Omega$ | Multimeter | | | | | | | |
| Z1=100 k$\Omega$ Z2=200 k$\Omega$ | 1x Scope Probe | | | | | | | |
| Z1=100 k$\Omega$ Z2=200 k$\Omega$ | Teensy | | | | | | | |
| Z1=10 M$\Omega$ Z2=20 M$\Omega$ | Multimeter | | | | | | | | 
| Z1=10 M$\Omega$ Z2=20 M$\Omega$ | 1x Scope Probe | | | | | | | |
| Z1=10 M$\Omega$ Z2=20 M$\Omega$ | 10x Scope Probe | | | | | | | |
| Z1=10 M$\Omega$ Z2=20 M$\Omega$ | Teensy | | | | | | | |

Effort Specification:

- [ ] At least half of the measurements are filled in with plausible values.
- [ ] Measured values also have a corresponding predicted value that shows understanding of the divider equation.
- [ ] Example calculation shows understanding of divider equations.
- [ ] Example calculation uses error propagation to find the uncertainty bounds in the output voltage.

Complete Specification:

- [ ] All measurements are filled in with correct values that match theory.
- [ ] Example calculation additionally shows understanding of loading effects and use correct instrument loads.
- [ ] All theoretical calculations (including the example calculation) correctly include loading effects and match measurements well. (i.e.: Predicted Output Voltage (Vrms) and Measured/Converted Output Voltage (Vrms) are within predicted error bounds of one another.)

{{< pagebreak >}}
## Fill in this table of properties for voltage dividers with op-amp buffers

This table uses the same column abbreviation as the previous section.

Provide example calculations showing how you calculated the predicted output voltage and the predicted uncertainty bounds for the case where there is an op-amp at the output.

| Op-amp at | VOPI (Vrms) | VOPC (Vrms) | VOM (Vrms) | $\lambda$ (V) | ERRI (%) | ERRC (%) |
|-----------|-------------|-------------|------------|---------------|----------|----------|
| input  | | | | | | 
| output | | | | | | 

Effort Specification:

- [ ] At least one of the measurements is filled in with plausible values.
- [ ] Measured values also have a corresponding predicted value that shows understanding of the divider equation.
- [ ] Example calculation is present and is theoretically appropriate.

Complete Specification:

- [ ] All measurements and calculations are filled in with correct values
- [ ] Example calculation additionally includes a 1-2 sentence explanation of how the op-amp is affecting the calculation and the measurement.  The explanation should make reference to appropriate op-amp input and output impedance properties.

{{< pagebreak >}}
## Extra Credit Writeups:

We don't provide complete specifications for extra credit writeups, but they will be graded for effort and completeness like normal sections.  You need to provide a "mini-report" of <1 page for each extra credit section that you attempt. Put a page break between each extra credit mini-report.