---
title: "E80 Project Design and Proposal"
---

Specifications: [html](/project/proposal/submission.qmd) [Word](/project/proposal/submission.docx)

Template: [html](/project/proposal/template.qmd) [Word](/project/proposal/template.docx)

Examples: [pdf](assets/Project%20Proposal_example_1_.pdf) [pdf](assets/Project%20Proposal%20_example_2_.pdf)

## Introduction

You will need to produce a project proposal and have it approved by **TWO** professors before spring break. The project proposal is made up of four parts: 

1. A one-page maximum written description of your experiment, 
2. A budget indicating what you intend to buy for the project, 
3. A mechanical drawing showing how you plan to mount or ruggedize the sensors for water submersion, 
4. A detailed schematic showing how you will connect your new sensors to power and to the Teensy. 

The following sections describe each deliverable. Note that an example proposal is linked above. 

## One-Page Description

You must write a one-page description of your project that lays out your scientific and/or engineering goals and describes how your sensor system will help you meet those goals. There are a few specific points that it should address:

* It should answer the question, "Why would anyone do this project?" or "Why should I care about your results?"
* It should outline your hypothesis and what you're comparing it to: what is the _x_ of your experiment, what is the _y_ and what two _x_-_y_ curves are you comparing? If you need to cite literature to establish your scientific relationship, then don't forget you can access papers through Mudd's network.
* It should state the sensors you are using and describe how they relate to your scientific/engineering goals. 
* If should, in text, describe where exceptional mechanical, electrical or software design is required.  No need to point out every op-amp, just fancy/abnormal stuff.
* It should convince the reader that you considered a number of design alternatives when you picked your project. The minimum bar for doing this is including five two-line project descriptions for projects that you considered but did not pursue.
* It should outline requests for specific launch times or locations for your robot. 

:::{.callout-note collapse="true"}
## Launch Locations

There are two locations we can launch in Dana Point: the public beach and the Ocean Institute pier. We have a limited number of launch slots on the pier: two teams can launch in each half hour slot from 8:30 a.m. to 2:30 p.m. If your scientific goals would benefit from a particular launch time slot or slots on the pier, then you should request those slots in this project description. If some time slots are oversubscribed, we will award them randomly.  We will prioritize giving every team that wants one a 
deployment off the pier over giving one team multiple deployments.  
:::


## Budget

You must prepare a budget for your final project.  **You have $50 to spend** on the project, and you may not augment that amount with personal money, student project grants or any other source of funds.  Your budget only needs to include sensors and other parts (e.g.: motors), and it should exclude parts that you plan to use from our inventory, which is freely available to you.  

To capture your budget, prepare a spreadsheet that contains the following for each part you intend to purchase:

* Plain English description.  e.g.: "Pressure Sensor".
* Part number. e.g.: "MPX5700".
* Unit price before tax and shipping.
* Tax costs.
* Shipping costs. Note that you can defray shipping costs by ordering multiple parts from one vendor.
* Link to vendor site.
* Link to datasheet.

Common vendors include [Digikey](http://www.digikey.com/), [McMaster-Carr](https://www.mcmaster.com/), [JameCo](http://www.jameco.com/), [SparkFun](https://www.sparkfun.com/), [AdaFruit](https://www.adafruit.com/) and many others.

Completing this budget will require you to name specific sensors and mechanical parts and to report their prices.  Therefore, you are expected to have selected parts for your experiment before submitting the budget. When you select parts, be sure to qualify them for your mission: do they have the necessary signal input range? an acceptable electrical interface? etc.

[Parts already in lab](/reference/inventory) are freely available to you, therefor this budget does not need to include parts that we already have in lab (since you won't buy them).  Some of the lab supplies, notably speakers and microphones, are not available for permanent installation, but they are available for temporary checkout for prototyping.  These supplies are cheap enough that we expect you to buy your own for permanent installation.

:::{.callout-note}
## Caveat emptor! i.e.: Let the Buyer Beware

* Surface mounted (SMT) parts are generally hard for students to work with.  You need to buy an adapter board for your part if you are buying something surface mounted.
* If you use a part with a digital interface, be careful of I2C, UART and SPI.  Using any of these will require a bigger software effort than sampling an analog signal.
* We have found that off the shelf ultrasound transducers don't perform well underwater.  Though it's hard, it's better to build your own out of our parts.
:::

Once you have prepared your budget, you must check it off and then submit a purchase order:

1. Get necessary approvals:
    - All purchases must be approved by your section instructor, who will initial your purchase requests on the tracking spreadsheet. 
    - All purchases must be approved by a second instructor, who will also initial your purchase request on the tracking spreadsheet.
    - You must ensure that the professors record your designated buyer; the **ONE** person on your team who is allowed to submit purchase orders.
    - You will not be approved if your order is over $50.  DO NOT FORGET TAXES AND SHIPPING when preparing your budget.
2. Prepare a purchase order: 
    - [New Purchase Order Request Form](https://www.hmc.edu/engineering/current-student-information/department-forms/)
    - Arrange for purchases to be shipped to the Engineering Department.
    - Include your team number and section number in a description field.
    - List Professor Brake as the professor to approve the purchase request.

Purchases have a relatively long lead time, around a week.  However, if your proposal is approved before spring break, then that lead time will be hidden by the break.


## Mechanical Drawings

You must prepare mechanical drawings of your robot.  

These drawings are intended to be concept drawings so that your professors can discuss the design with you, not full models for manufacturing.  Therefore, please sketch these drawings (either by hand or in a drawing program) and please DO NOT provide a SolidWorks model. 

Your mechanical drawings should allow a professor to evaluate important design decisions. Therefore, do the following:

* Indicate motor locations. Careful to keep them as far from your IMU as possible to keep the magnetometer happy.
* Indicate sensor locations.
* Indicate penetrator locations and note the number of wires passing through each penetrator.
* Sketch the wiring harness and how it's fastened to the robot.
* Include approximate calculations of mass, center of gravity, buoyancy, center of pressure, and (if necessary) ballast.
* If you're doing something bold, calculate the required torque for your motors. Motor datasheets can help.
* Include a brief paragraph summarizing major design decisions. e.g.: "It's flat and wide because we wanted a raft."


## Schematics

Make a schematic that adheres to good practice (as outlined in [lab 3 specs](/labs/lab3/submission.qmd)) and that includes all of your sensor interface circuits. Your schematic should be a comprehensive design document, so do the following: 

* Show every wire, resistor, capacitor (don't forget bypass capacitors), and power source (i.e.: battery) that you intend to assemble into your final design.  
* Annotate the expected Voltage swing on every node of the schematic.
* Check that none of the Teensy pin nodes swing above 3.3 V or below 0 V.
* Where appropriate, include relevant reference designs from datasheets (with citation) to justify your schematic choices.
* Though we're not requiring simulations of your design here, having a working simulation of the design is a great idea.
* Split this big schematic into multiple smaller ones if it makes it easier to read. (It may still make sense to submit one big schematic, but consider whether a big schematic or several small ones will serve you better.)

All of your new electronics will be assembled on a new board called the [protoboard](https://drive.google.com/open?id=1VT_N11I8Alo8cQPUag5moUuXnGed80gd).  We discuss the protoboard in greater detail during the project [build](/project/build), but its limited size should inform your circuit design.  The protoboard has the same number of rows as a standard breadboard, so don't pick designs that require more wires than would fit on a breadboard. As a reminder, you can find the design details for all the PCBs you will use on the [boards](/reference/board) page, and those design details can help when planning out your final project. 


