---
title: E80 Project Proposal Checkoff Checklist
toc: false
format:
  html: default
  docx: default
---

Date: 
Section #:
Team #:
Professor: 

Proposal:

- [ ] Has a justifiable scientific goal
- [ ] The specified sensors will help achieve that scientific goal
- [ ] Some sense of whether signals are big or small. Are the measurements feasible?
- [ ] List exceptional or difficult design features of their robot
- [ ] Have considered whether specific launch times are beneficial to them. Make requests for specific times if need be. (Don’t forget that human activity is much lower in the morning.)
- [ ] Robot will deploy autonomously for one minute
- [ ] Three new sensors with two unique electrical interfaces will be installed
- [ ] Have listed five alternative project ideas

Budget:

- [ ] Are not purchasing any parts that we have in lab (Students may buy replacement speakers or pH probes because they are not available for permanent installation.)
- [ ] Justify any high cost sensors: students are not buying things that we can easily make
- [ ] Checked that sensors are not SMT or that students have sensors on breakout boards
- [ ] Checked interface type for each sensor is compatible with Teensy
- [ ] Included taxes and shipping costs in the budget
- [ ] Total cost less than $50
- [ ] Verified team knows about engineering purchase order request form
- [ ] Verified the team has a designated buyer & knows not to buy until they’re 2x checked
- [ ] Have plans to generate fake sensor outputs next week if parts have not arrived

Mechanical Drawing:

- [ ] Mass calculated
- [ ] Center of gravity calculated (especially if they have a winch)
- [ ] Center of buoyancy calculated
- [ ] Ballasting calculations? (if applicable)
- [ ] Will it float? (Or not float if that’s the desired behavior)
- [ ] Low profile against wind? (unless designed for high wind drag)
- [ ] Low profile against currents? (unless designed for high current drag)
- [ ] Thrust calculations for unusual behaviors (e.g.: do you really generate enough thrust to bury yourself in the sand? To submerge? To hoist that winch?)
- [ ] Sensor placement good for measuring desired quantities
- [ ] Motors as far away from IMU as possible (to avoid magnetic field interference). Try for at least 30 cm.
- [ ] Plans for cabling if sensors are far away
- [ ] Planned out a suitable number of penetrators for waterproof box.  Have picked locations.
- [ ] What is waterproof and what is not?  Plans for waterproofing sensors out in the water.

Schematic:

- [ ] Bypass capacitors for every op-amp
- [ ] Voltage swings annotated on every node, including sensor outputs
- [ ] Designed gains lead to the voltage swings specified on the design
- [ ] Do the designed offsets prevent clipping?
- [ ] Inputs to Teensy bounded between 0 V and 3.3 V
- [ ] Signals buffered appropriately, especially as they enter the Teensy
- [ ] Are there enough input channels on the Teensy, do they plan to use the extra pins?
- [ ] Are there enough digital interfaces on the Teensy, are they on the right pins? (if needed)
- [ ] Considered software needed to interface with digital sensors? (Don’t forget that this includes encoders & Hall flow meters. Weather vanes often easier as potentiomenters.) 
- [ ] Have they picked good H-bridges for any extra motors they plan to use?
- [ ] Considered how to measure any audio signals?  Are they using an envelope detector + analog channel or are they designing their own sampler in software?
- [ ] Is battery power sufficient to peak current load?
- [ ] Calculated average current draw and maximum mission life? (It can be helpful for debugging to annotate current for each branch.)
- [ ] Considered how to generate signals for sensors that require them? (e.g.: AC signals for salinity sensor?)

Administrative/Overall:

- [ ] Prof advised team on expected difficulty of their proposed project, made sure they all bought in. Especially important if the team is trying to do lots of fancy stuff.
- [ ] Prof reminded team of the importance of experimental design and measured data in the final evaluation of the projects.
- [ ] Prof reminded team of checkoff schedule for next three weeks -- breadboard, soldered and integrated, deployment at BFS
- [ ] Prof updated the instructor checkoff spreadsheet in the Project folder (this is important so that Prof. Brake can approve purchase orders)
