---
title: "Reference Designs"
---

## AUV Turbidity Meter

This design adapts the lab turbidity meter to the requirements for being immersed and waterproofed. The instructions and procedure are [here](https://drive.google.com/open?id=1RYaInz-txbC4iaJD83_0HSwKYBlVGDN1HlEs4yDEMjM). A zip file of the design files is [here](https://drive.google.com/open?id=10QO_RUk4GNhHB0n_1xPkC-ebEDFHg0sX).


## Anemometer

An anemometer is used for measuring wind speed. It is useful for a surface vehicle, but not so much for a submersible. The instructions and procedures are [here](https://drive.google.com/open?id=1rY2bEjX3RP1EuHBjaoB50aiPz61I9q4W86KAzeNQdSo). A zip file of the design documents is [here](https://drive.google.com/open?id=10PVtvyJ87abJO67Chued8QdySKAWsk1L).


## Weather Vane

A weather vane is used for indicating wind direction relative to the local coordinates of a surface craft. It is not so useful for a submersible. There are two possible sensors for the weather vane. The first is the MLX90316. The instructions and procedure are [here](https://drive.google.com/open?id=1f8EBwjwC41yVn9NPL-A11Ml1rJ3tqBN0ptcQc6E8O4U). The second is the ACE128. The instructions and procedures are [here](https://drive.google.com/open?id=1nxSudsfMWcUmk4KY5xAjlgvL6IgpMP_TdypqefZIsCw). A zip file of the design files for both is [here](https://drive.google.com/open?id=10XoZwejIFrBTcVLfXJGrxdgBVczbB9Cn).


## Velocity Sensor

The reference design for the velocity sensor was not terribly successful. Perhaps you can learn from other's mistakes. The instructions and procedures, such as they are, are [here](https://drive.google.com/open?id=1i0zIxPvECrV4dE9XiX8ruwt7mzBVitFCy8Mf-ID--Qk). A spreadsheet with the design calculations is [here](https://drive.google.com/open?id=1H4uxriuP9vmXTxEPW2_xlxATGKS0cJR1Ro92NOTeYJc). A spreadsheet with the experimental results is [here](https://drive.google.com/open?id=17crtsGbjBhGFo32qSEhczJHauxY05IONGZRKeeFRNcI). A zip archive with the design documents is [here](https://drive.google.com/open?id=10QkiZIVQhM2UwSnC5YuN2zTD1xlhsCxi).

Salinity Sensor


## Future Designs

If you had a design that was particularly successful and you would like to share it with future generations of E80 students, let the professors know, and it may show up here.
