---
title: "Lab 5 Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

Keep answers as short as possible while still meeting specifications. Submit as a PDF.

Team Number:

Team Member Names: 

All schematics in this report should adhere the following specification:

- [ ] Include the stimulus for the circuit on the left
- [ ] Include power supply connections and bypass capacitors.
- [ ] Annotate each node with a name, using the name Vin for the input voltage and Vout for the measured output voltage
- [ ] Annotate each resistor and capacitor with a component value.
- [ ] Use implicit connections to connect the power supplies.
- [ ] Use the op-amp symbol to indicate operational amplifiers (instead of, e.g., a pinout diagram), but annotates that symbol with the chip used to make the op-amp.
- [ ] Represent op-amp circuits in their typical configurations, so that they look similar to videos.  Don't use non-typical drawings that make one type of op-amp circuit look like another.  (e.g.: don't draw a non-inverting amplifier with feedback on the top of the op-amp; that's usually how inverting amplifiers are drawn.)
- [ ] Generally keep signal flow left-to-right
- [ ] Generally keep high voltages at the top of the diagram and low voltages at the bottom.
- [ ] Space out components well enough and zoom in close enough that annotations are easy to read.
- [ ] Minimize unnecessary crossings, corners and jogs in the wires.  Use connect-by-name to reduce congestion among wires.  This [tutorial](https://learn.sparkfun.com/tutorials/how-to-read-a-schematic/reading-schematics) has more information.

All pictures of circuits in this report should adhere to the following specification:

- [ ] Picture is taken at a level of lighting and zoom that allows a reader to trace connections in the circuit.
- [ ] The circuit is neatly laid out so that readers can trace connections in the circuit.

{{< pagebreak >}}
## Report on the FFT of Signals Directly Applied to the Scope

The manual for this section requests five oscilloscope traces, which will be referred to here as traces 1-5 based on the list below. Traces should follow the instructions in the manual (50 cycles on screen, FFT span is 100 kHz, FFT center is 50 kHz). Further, the input signal should be on channel 1 and the math mode should be scaled to be clearly visible:

1. Signal 1
2. Signal 2
3. Signal 3 with rectangular window
4. Signal 3 with Hanning window
5. Signal 3 with rectangular window and changed x-axis

The manual also requests two Matlab plots

1. Matlab plot of FFT magnitude for signal 3 with rectangular window
2. Matlab plot of FFT magnitude for signal 3 with Hanning window

These traces and plots should be included in this section with a specific organization.  They should be displayed as five side-by-side pairs of figures, each with ~1 sentence commenting on the differences between the left and the right figure.  The commentary should specifically relate the changes to FFT theory.  The pairs are:

- [ ] Trace 1 vs. Trace 2
- [ ] Trace 1 vs. Trace 3
- [ ] Trace 3 vs. Trace 4
- [ ] Trace 4 vs. Trace 5
- [ ] Trace 3 vs. Matlab Plot 1
- [ ] Trace 4 vs. Matlab plot 2

Effort:

- [ ] Includes all side-by-side comparisons described in this section.
- [ ] All plots adhere to instructions in this section and in the manual (50 cycles on screen, FFT span 100 kHz, FFT center is 50 kHz), and all plots are easily legible.
- [ ] Includes a derivation that explains how frequency peaks in signal 3 relate to the input frequency and the shape of the wave.

Complete: 

- [ ] All 1 sentence descriptions correctly relate features in side-by-side comparisons to FFT behavior.
- [ ] Derivation of frequency peak locations is succinct and correct.
- [ ] Includes a further 2-3 sentences discussion of windowing functions explaining how they work (by appealing to Fourier analysis) and what the tradeoffs are in choosing one over another.

{{< pagebreak >}}
## Report on Design and Characterization of Microphone Interface Circuit

Effort:

- [ ] Provides a picture of the microphone interface circuit, including the microphone.
- [ ] Provides a schematic of the microphone interface circuit, including the microphone.
- [ ] Includes some good-faith calculations predicting the bandwidth of each amplifier stage in the interface using the gain-bandwidth product.

Complete:

- [ ] Calculations of gain-bandwidth product are correct
- [ ] Provides an oscilloscope trace of the hand clap with overlaid FFT.  The horizontal axis on this trace should be scaled to capture the entire clap, the vertical axis should be scaled so the time domain signal is as large as possible without clipping, the vertical offset should be set to 0V.  The FFT span and center should be set to clearly show clap frequencies. Trace must be exported using screen capture, not a cell phone photo.
- [ ] The clap signal shows proper circuit operation: clap signal is centered at 0V, clap peak amplitude is measured as > 100mV.
- [ ] Brief discussion of what frequencies are present in the hand clap and how those frequencies compare to the range of human audible frequencies and to the range of typical human speech.

{{< pagebreak >}}
## Graphs of Microphone Voltage vs. Position for Beacon-Based Localization

Effort:

- [ ] Makes claims about which beacon emits each frequency, and includes pictures and oscilloscope traces that support the claims.
- [ ] Include three plots of received Voltage magnitudes vs. distance, one for each emitter. Plots are clearly legible and labeled.

Complete:

- [ ] Includes calculations suggesting how frequently multipath patterns will repeat in data and how close to space x-axis samples to capture those patterns.
- [ ] Plots show multipath effects overlaid onto typical magnitude decay behavior.
- [ ] Analytical model for received Voltage magnitude is overlaid onto the plots.

{{< pagebreak >}}
## Graphs of Microphone Voltage Sampled at Different Frequencies with Teensy Rig

Effort:

- [ ] Includes plots of FFT magnitude for 10 kS/s and 100 kS/s data. Plots are legible and labeled so it is clear which is which.
- [ ] Includes plots of time samples for 10 kS/s and 100 kS/s data. Plots are legible and labeled so it is clear which is which.

Complete: 

- [ ] Explains discrepancies between measured data and data that is being transmitted in the tank using appropriate theory.  4-5 sentences.
- [ ] Includes calculations of minimum sampling rate for the tank.
- [ ] Includes plots of time data and FFT magnitude for tank data sampled at the minimum frequency.

{{< pagebreak >}}
## Extra Credit Writeups:

We don't provide complete specifications for extra credit writeups, but they will be graded for effort and completeness like normal sections.  You need to provide a "mini-report" of <1 page for each extra credit section that you attempt. Put a page break between each extra credit mini-report.

