---
title: "Lab 5 Writing Assignment"
subtitle: Mathematical Derivations and Equations
---

## Writing Assignment

In this writing assignment you will learn to write a rigorous mathematical derivation.
You will present a Fast Fourier Transform (FFT) calculated using MATLAB of a simulated square wave and provide a derivation of the square wave FFT to justify the frequency components and power levels present in the signal.

## Statement of Work

Create a short MATLAB script to simulate an 11 kHz square wave with an amplitude 1.5 V and an offset 0 V.
You can do this however you would like, but the following code will work.

``` matlab
N = 100; % Number of points
freq = 11e3; % Frequency [Hz]
period = 1/freq; % Period [s]
dt = period/10; % Sampling period [s]
t = 0:dt:(N-1)*dt; % Time vector [s]
A = 1.5; % Wave amplitude [V]
y = A*square(2*pi*freq*t); % Create square wave (Note: must have the signal processing toolbox installed to use square())
```

Provide a rigorous mathematical derivation explaining your results from taking the FFT of this square wave.
This is similar to a theory/background section of a standard engineering lab report.
Also include a MATLAB figure showing the FFT (calculated in MATLAB) of your simulated time domain square wave data.
Explain your derivation and use it to justify the power levels and frequency components in your measured data by writing 5-7 paragraphs of accompanying text.
Pay attention to units on the x and y axes of any FFT you analyze, and justify how to change between different units. 
You may include other figures if needed.

The document should contain as many mathematical equations and/or figures as you need, and five to seven paragraphs that describe the mathematical derivations and draw conclusions about the FFT. 
You must include equations in your text and reference them properly.
In this assignment you may need to reference the laboratory manual, MATLAB documentation or mathematical references that you referred to when putting together your derivation. 
Though you don’t need to write a full-fledged introduction to the experiment, you will need to be mindful to orient the reader in the first paragraph.

Be mindful of tense. 
Tense should always agree within a paragraph, but could vary within a report. 
Describing the methods in past tense (e.g.: “the voltage was measured”) and the future work in future perfect (e.g., “the voltage will be used to pick a resistor”) is reasonable. 
Be sure to avoid use of the first person including saying “we” or “the team,” both of which count as first person because you are implying the presence of an experimenter. 
Two ways to avoid first person are using passive voice (discouraged where possible) and making the technical artifact the subject of the sentence.

Here are some examples:

| 1st Person           | Passive Voice         | Result as Subject | Notes                                                                  |
|------------------|------------------|------------------|------------------|
| We measured salinity | Salinity was measured | The salinity was  |                                                                        |
| We drove the robot   | The robot was driven  | The robot drove   | Careful! “Passive voice” and “result as subject” say different things! |

## Learning Objectives

By the end of this writing assignment you will...

-   Format and present equations in text
-   Write text to support your derivation

## Required Resources

-   [ ] Figure of an FFT of a square wave using simulated data. Your FFT should be calculated in MATLAB from the time-domain trace of the square wave.

## Specifications

### Effort

-   [ ] Contains equations to mathematically describe FFT of square wave
-   [ ] Figure present with FFT computed in MATLAB overlaid with analytical FFT.

### Completion

#### Mathematical Derivations

-   [ ] Contain a label that numbers each equation in the derivation
-   [ ] Each equation is referenced in the text
-   [ ] Variables of the derivations are described in the text
-   [ ] Derivations are written out explicitly to show a sequence of steps
-   [ ] Steps in the derivation proceed logically from one another in an appropriate level of detail for the audience
-   [ ] Refer to appropriate theorems covered in class where appropriate, don’t reinvent every wheel

#### Figures

-   [ ] Include FFTs from your measurements for comparison to your theoretical analysis.
-   [ ] Proper Axis Labels & Tick Size, Readable: appropriate fonts, line weights and data markers and not overly cluttered, follows other figure conventions from previous weeks.
-   [ ] Correct Units on both X and Y Axis.
-   [ ] Shows interesting features of frequency spectrum of the tested signal.

#### Text

-   [ ] Refers to each derivation/figure.
-   [ ] Correct sentence mechanics like cohesion and coherence between sentences and no run-ons.
-   [ ] Correct paragraph mechanics like topic sentences and placement at breaks between ideas.
-   [ ] Language is not stilted and jargon is kept to a reasonable minimum.

#### Technical Inferences in Text

-   [ ] Verify the correctness of your theoretical results by referring to FFT Figure, which includes justifying both the power levels and frequency components of your measurement.
-   [ ] Use continuous and discrete Fourier transforms and notation where appropriate to discuss the derivation of your transform and your MATLAB plot.
-   [ ] Mathematically correct and insightful analysis of your input signal explains the output.

## Resources

-   This document is a great place to start: “[How to Use Mathematical Equations in Your Thesis](https://gradstudents.carleton.ca/2014/use-mathematical-equations-thesis/)”, by Rozita Rashtchi.
-   Make sure you refer to equations as “Equation 1” or "Eq. 1" not “eq 1” or any other way, and be sure to include units wherever appropriate. Units should not be italicized.
-   Pages 4-8 of the “[User’s Guide for the `amsmath` Package](https://texdoc.org/serve/amsldoc.pdf/0)"