---
title: "E80: Experimental Engineering"
---

## Welcome!

E80, Experimental Engineering, is a sophomore-level, semester-long required course, in which students conduct multiple experiments covering a number of engineering disciplines. 
These experiments are a training ground for a final project: a field deployment where student teams measure phenomena of their choice. 
Experimental Engineering is an essential part of the engineering curriculum at Harvey Mudd College, and has been offered as a course for over twenty years.
Its predecessor E54 - which had more experiments and no field experience - was also offered for more than 20 years. 

The primary purpose of the course is to teach basic instrumentation and measurement techniques, good lab report practice, technical report writing, analysis and presentation of data, the usage of experimental results for engineering design purposes, and the beginnings of professional practice. 
In 2008 the course was revamped to change the field experience to flying fully-instrumented model rockets. In 2017 the course was revamped again with yet another new field experience: deploying fully autonomous underwater robots. 


## Faculty and Office Hours
| Name                | Day                    | Hours                                          | Location |
|---------------------|------------------------|-------------------------------------|----------|
| Matthew Spencer     | Monday                 | 9:30 am to 11:00 am and<br>1:00 pm to 4:00 pm  | Parsons 2358         |
| Ethan Ritz          | Monday/Wednesday       | 4:00 pm to 5:00 pm                             | Middle tent in Strauss plaza 	    	|
| Qimin Yang          | Tuesday                | 9:00 am to 11:00 am                            | Parsons 2365  		|
| Josh Brake          | Tuesday                | 1:00 pm to 3:00 pm                             | Tent outside Parsons  		|
| Dre Helmns          | Wednesday              | 1:00 pm to 3:00 pm                             | Parsons 1292C  		|

You may attend any office hours, not just your section professor's.


## Meeting Times

- <u>Lab Section 1</u>:\
  Tuesday 1:15 p.m. to 5:15 p.m. in Parsons B171 &  B181 		(Prof. Helmns)

- <u>Lab Section 2</u>:\
 Wednesday 1:15 p.m. to 5:15 p.m. in Parsons B171 & B181 		(Prof. Yang)

- <u>Lab Section 3</u>:\
 Thursday 1:15 p.m. to 5:15 p.m. in Parsons B171 & B181		(Prof. Ritz)

- Writing and Reflection for all sections - Friday 1:15 p.m. - 3:15 p.m 
  - Section 1 - Shan 2440
  - Section 2 - Shan 2450
  - Section 3 - Shan 2454

After spring break: There will be open lab hours in Parsons B171 & B181 during the normally scheduled lab times.

Students may only work in the E80 labs when a professor, staff or a proctor opens the lab.  Any team may use the equipment in the labs during a lab section, but teams that are scheduled for the section have top priority for the equipment. 

## Mask Policy
Masks will be required for all E80 activities until further notice.

## Digital Communication
- [https://github.com/HMC-E80/E80](https://github.com/HMC-E80/E80) This is our Github repository, which lets you use Git to acces E80 software. Git is a distributed version control system where you can copy source code and track changes to the code. [Lab 0](/labs/lab0) will walk you through the steps to configure Git on your computer.
- [https://discord.gg/Eu7gFZKgcj](https://discord.gg/Eu7gFZKgcj) This is an invite to our Discord server.  All digital communication and asynchronous help requests will go through Discord, so default to messaging there instead of emailing us.
- [https://harveymuddcollege.instructure.com/courses/1097](https://harveymuddcollege.instructure.com/courses/1097) This is our Canvas site. We will use Canvas to collect your assignments, receive your quiz responses and record your grades.
- All other information for the course is distributed on this website.


## Course kit fee
- There is a $65 kit fee per student. This fee can be waived in cases of financial hardship. Course instructors will not know about waiver requests.
- Kit payment can be made [here](https://docs.google.com/forms/d/e/1FAIpQLSfLGyW_zk6jB89jHjIme0mkHV_LVAtXeJSDNIf7njMEDN1t1w/viewform).
- Kit waiver request can be made [here](https://docs.google.com/forms/d/e/1FAIpQLScM-5lYfwQAE_5v6WAz357C1cftwr4sNQRPj4dC_GaPD-ihvw/viewform).


## Team and Group Assignments

Almost all work in E80 is completed in teams.  Some details about teams are below.

- Teams are assigned before your first laboratory meeting.
- These assignments will be made using whatever method your instructor desires, and the nominal team size is four members.
- Sometimes registration limits in a class will require teams of three or five members to be formed.
- These teams are designated using a 2 digit number where the first is your section number and the second is your team's number (e.g. section 1's team 1 is 11).
- You must report your team number on all assignments. 
- For three of the labs (2, 3, and 4), you will need to split your team into 2 sub-teams.
- A different sub-team must be used for each of these Labs.
- Team assignments will be for the duration of the course.
- If you're having problems on your team, talk to a professor or staff member *early* so we can try to help.

Team assignments can be found on the [People tab on Cavnas](https://harveymuddcollege.instructure.com/courses/1097/users).

## Graded Submissions

### Graded Submissions Breakdown

::: {.center-table}
| Item                           | Weight |
|--------------------------------|:------:|
| [Lecture Quizzes](#lecture-quizzes)                |   7%   |
| [Surveys and Team Check-Ins](#surveys-and-team-check-ins)     |   6%   |
| [Laboratory Submission Sheets](#laboratory-submission-sheets)   |   32%  |
| [Laboratory Writing Assignments](#laboratory-writing-assignments) |   15%  |
| [Technical Memorandum](#technical-memorandum)           |   10%  |
| [Final Presentation](#final-presentation)             |   10%  |
| [Final Report](#final-report)                   |   15%  |
| [Participation](#participation)                  |   5%  |
:::

### Turn-In on Canvas

All assignments that you need to complete, including links to quizzes, can be found in the [Modules tab on Cavnas](https://harveymuddcollege.instructure.com/courses/1097/modules).  You will always turn in assignments on Canvas or complete quizzes/surveys linked from Canvas.

### Specifications Grading

The grading in E80 for submission sheets and writing assignments is based on whether or not your deliverables meet two different levels of specifications: **effort** and **completion**.
The overall grade on an assignment is determined by how many of the sections meet either effort or completion.

Effort specs describe **good-faith effort** whereas completion specs describe **correctness**.

In most situations, completing all the effort specs is equivalent to a passing grade on the assignment.
The remaining sections of completion specs raise your grade from a passing grade to full credit.

If the initial version of a submitted assignment does not meet specs, it may be revised according to the stipulations of the course [resubmissions policy](#resubmission-policy).

### Graded Submissions Details

#### Lecture Quizzes

- There are seven video lecture sets that you are expected to watch. Each of these video sets has an associated online quiz. You must take each of these quizzes individually.  

- You may not talk to other people in order to take the quiz, but they are open book, notes and internet.  The one exception to the 'no people' rule is that you may speak with a professor to clarify ideas before you open the quiz associated with the lecture set. 

#### Surveys and Team Check-Ins

- You will be called upon to complete surveys at the beginning, middle and end of the class, and each week, you will be asked to complete a team check-in (a quick peer evaluation) for the lab done that week. Completing each of the check-ins is worth 0.5% of your grade, and completing each of the longer surveys is worth 1% of your grade.

- There are a total of 6 weekly check-ins (from weeks 2 through 7) and they are due each Friday at 3:30 pm.

- These are individual assignments

#### Laboratory Submission Sheets

- There are a total of 8 labs in the class: Lab0 through Lab7. You must submit a submission sheet for each of the labs that contains data you collected during the lab. (Though note that in lab0 the Matlab on-ramp deliverable is the submission sheet.) This submission sheet will be evaluated for correctness: it's a way of assessing whether your experimental procedure was correct during the lab. Each submission sheet you provide will be worth 4% of your final grade.

- These are group assignments, so there will be only one submission per team.  The Matlab onramp for lab 0 is an exception: it is an individual assignment.

#### Laboratory Writing Assignments

- You will be required to complete a writing assignment after labs 1-5. The purpose of the writing assignments is to train you in specific aspects of scientific writing: making figures, using tables, equations, etc. These assignments are completed entirely on Friday in the Writing and Reflection section. Each writing assignment will be worth 3% of your final grade, and you submit five assignments for a total of 15%.

- These are individual assignments.  The team contract exercise in week 0 is an exception, there should be one team contract submission per team.

#### Technical Memorandum

- Each student will write an individual technical memorandum on material covered in Lab 6. See the [Lab 6](labs/lab6) page for more information.  

- You must submit a tech memo to pass the class.

#### Final Presentation

- Each team will make a final presentation during Presentation Days, on Wednesday, May 1st, 2024. A detailed schedule will be posted ASAP. The presentation is 15-minutes long followed by a 10-minute Q&A session. The Final Presentation guidelines and rubric are found on the [Final Project Report and Presentation page](/labs/project/report).

#### Final Report

- A final technical report will be submitted by each team on the results of the final AUV deployments. The report will be graded for both technical content and proper use of [technical English](https://www.mit.edu/course/21/21.guide/). A rough draft of your final report is due at 11:59 PM on 4/26/24. The final draft is due at 11:59 PM on 5/1/2024. The Final Report guidelines are found on the Final Project page.

#### Participation

- The instructors will assign you a participation grade which is determined by their in-lab observations, your peer evaluations, and your regular progress through the project checkoffs.

## End-of-Semester Grades
Grades will be awarded on a standard grading scale (93.3% is an A, 90% A-, 86.6% is a B+, etc ...) based on your total individual score.
The professors reserve the right to award grades more leniently than this grading standard.  

## Course Calendar

A Google Sheet with the key dates and assignments in E80 can be found [here](https://docs.google.com/spreadsheets/d/1qR7HhVNWtqK8va9gGP6NGhX_NoIblt1x9VRRuFam1ng/edit?usp=sharing).

You can also review the [Modules tab on Cavnas](https://harveymuddcollege.instructure.com/courses/1097/modules) for a week-by-week breakdown of what's due with links to refernece material and where to turn stuff in.

## Course Policies

### Attendance and Tardiness
Students sometimes have to miss E80 labs for an assortment of reasons.  The instructors don't record attendance because we assume that groups will work to equitably account for absences or tardiness. For example, if your group has a member with a planned absence for a particular lab, then you and your teammates should discuss how to shift more prelab work to the person who will be absent. If you don't feel like everyone is pulling their fair share, talk to your group and talk to an instructor so we can help you navigate the situation.

### Late Work Policy
No late work is accepted. You will receive no points for work submitted after deadlines. 
This is in keeping with good professional practice.  Some assignments may allow for multiple attempts and resubmission, but the first attempt always needs to be submitted by the appropriate deadline.

### Incomplete Grade Policy
Incomplete grades will be granted only in rare circumstances and require the approval of the instructor.

### Pre- and Post-Lab Work Policy
The amount of time that you are free to work in lab is restricted. We enforce these restrictions for three main reasons: 

(1) to simulate demands that can arise in real-world engineering, 
(2) to help students internalize the learning goals of the class, and 
(3) to help keep E80 to a smaller time footprint.

You are allowed to work in any way you would like on  before a lab (pre-lab) as long as you do not touch any hardware.
You may NOT collect data (for your experiment), manipulate or test hardware, populate a protoboard, or use the laboratory equipment outside of your lab hours. 
However, you may look at datasheets, write software, calculate expected results, prepare Excel sheets to do calculations in lab, ask how equipment works, run your preparations by professors, and pursue a variety of other activities.
You can spend as much or as little time desired on the pre-lab activities, but successful teams spend a lot of time and energy before the lab starts.

The post-lab period is for reflection, resubmission when it's allowed, and taking a break from E80. 
You may NOT collect data, manipulate or test hardware, populate a protoboard, or use the laboratory equipment outside of lab.
However, you may freely reprocess any data that you have already collected during a lab section.
This includes, but is not limited to, writing MATLAB code for processing and visualizing your data.

When in doubt about whether an activity is acceptable outside of lab, ask.

### Resubmission Policy

Lab submission sheets and writing assignments in E80 are able to be resubmitted without penalty if they do not meet completion specs on the initial attempt.
To be clear, this means that resubmitted assignments are worth the same amount as initial submission and full credit can be earned even if the initial submission does not fully meet the specifications.

The resubmission policy is subject to the stipulations listed below:

1.  You must submit **something** by the assignment deadline.
    - Don't phone this in because there is limited time for resubmission.
2.  After you receive feedback, you can revise your submissions until spring break.
    -   Most of specs can be done outside of lab with data.
    -   However, if you weren't able to get good data, there is one week before spring break where you can go back to collect more.
3.  Resubmissions are checked off by an instructor during office hours.
4.  For all submissions, you will need to self-assess **before** you submit. Every assignment you submit should be accompanied along with a checklist of specs that you believe the assignment meets or does not meet.
5.  All resubmissions must be completed by spring break.

### Cooperation Between Teams
Cooperation between teams is limited.
The rules for each period of the week (pre-lab, during lab, post-lab and writing and reflection) are below.
In this section, the word group will refer to a full team of students during a normal week or a sub-team of students during weeks where teams are split into sub-teams.

1. Pre-lab: A group may discuss the lab with another group to make sure they are clear on concepts and understanding. Groups may not share code, writing, or documentation with other groups.

2. During Lab: Groups cannot work together, discuss concepts or understanding, share data, share code, or share writing.  Groups may arrange to swap hardware to debug and test defective parts of an experiment or device, but they should strongly consider elevating their concerns to an instructor if part swaps are necessary or if parts are being destroyed.

3. Post-Lab: Groups may work with other groups in the same way as the prelab: they may discuss concepts and understanding (including talking about the scale of measured results from lab).

4. Writing and Reflection: Each student should be producing an individual work product and may not exchange code or writing with other students.  Data may be shared among a group, but not between groups. 

These work restrictions are relaxed during the final project (after spring break): Groups may work on their robot at any time and may discuss any aspect of their robots with one another (as if the prelab policy always applies).  

### Sharing Rubrics
We will be returning/releasing graded lab report rubrics throughout the semester.
It is an HONOR CODE VIOLATION to share these rubrics with other teams or with students enrolled in future versions of E80.

### Access to Lab During the Final Project
- Students may work in the labs any time that it is open.
- Students may only work in the E80 lab when a professor, staff member or proctor opens the lab.
- Any team may use the equipment in the E80 and electronics labs during a lab section, but teams which are scheduled for a section have top priority for the equipment. 

### Accessibility and Accommodations

Harvey Mudd College strives to make all learning experiences as accessible as possible. If you anticipate or experience academic barriers based on your disability (including mental health, chronic or temporary medical conditions). If you have any questions, please contact the Office of Accessible Education at [access@g.hmc.edu](mailto:access@g.hmc.edu). Students from the other Claremont Colleges should contact their home college's disability officer. You also need to register with the [Office of Disability Resources](https://www.hmc.edu/student-life/disability-resources/). to establish reasonable accommodations.

### Academic Honesty/Plagiarism

**Each student will be responsible for observing HMC's Honor code and abiding by the Standards of Conduct:**\

> “All members of ASHMC are responsible for maintaining their integrity and the integrity of the College community in all academic matters and in all affairs concerning the community.” --<cite>ASHMC Constitution</cite>


1. Thoughtful respect for the rights of others;
2. Honesty and integrity in both academic and personal matters;
3. Responsible behavior both on and off campus;
4. Appropriate use of campus buildings and equipment, and;
5. Compliance with College regulations and policies.

